### ISSUE TITLE
Garbled interface in alsamixer.

### ISSUE THREAD

**Issue by bitcrazed** [Microsoft/console#101]
_From @Vaporeon on May 21, 2017 11:23_

I run Windows inside a virtual machine with KVM and PCI passthrough.
In order to change the volume for the host I ssh back into it and change the Line volume with `alsamixer`

Although the program works the text interface gets messed up.
![alsamixer](https://cloud.githubusercontent.com/assets/12814075/26283412/5750f552-3e6b-11e7-8b1e-dc045dc21078.PNG)

To reproduce ssh into any machine configured to use ALSA audio and run `alsamixer`.

Windows Version:
Microsoft Windows [Version 10.0.15063]

_Copied from original issue: Microsoft/WSL#2136_

**Comment by bitcrazed** [comment]
_From @zadjii-msft on May 22, 2017 16:58_

@Vaporeon What font are you using?

**Comment by bitcrazed** [comment]
_From @Vaporeon on May 23, 2017 3:26_

The default which is Consolas 16 I believe. I am also using 150% DPI scaling.

**Comment by bitcrazed** [comment]
_From @Vaporeon on May 27, 2017 15:38_

Changing the font does indeed fix it. It's too bad as Consolas is my favorite font among the stock ones and adding custom fonts to the Windows Console is not exactly fun. I tried TTF Terminus but it wouldn't take.

**Comment by bitcrazed** [comment]
_From @zadjii-msft on May 30, 2017 16:21_

Uhg. That's unfortunate, Consolas is the font that usually always works. I'll take a closer work.

Most monospace fonts work automatically now, no need for dirty registry hacks like in the past. Just install the fonts on your system and go

**Comment by bitcrazed** [comment]
_From @zadjii-msft on July 13, 2017 22:16_

I've been having some troubles getting this reproduced locally. @Vaporeon Could you try copying and pasting the "garbled" characters here, or in a txt file or something? 

If I had to guess, I'd say this is very likely going to be fixed by a change miniksa put in around the same time I fixed #1879. We're cropping certain characters a little differently now, so that graphical issues should be harder to come by.

I believe those characters are fixed now, so I'm going to remove the bug label from this.

**Comment by DHowett-MSFT** [comment]
It looks like this is fixed, so I'm going to close this issue.

![image](https://user-images.githubusercontent.com/14316954/52320981-1881e300-2987-11e9-8acc-b3e13b097e00.png)
