### ISSUE TITLE
Scrolling doesn't work properly in latest insider beta

### ISSUE THREAD

**Issue by bitcrazed** [Microsoft/console#111]
_From @warpdesign on April 22, 2017 10:22_

This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.16179
* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
I ran npm installed which produced lots of output text and wanted to scroll up to read the text I missed.
* What's wrong / what should be happening instead:
Instead of seeing the output from the command I just typed, I saw output from a command I ran hours ago.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

_Copied from original issue: Microsoft/WSL#1984_

**Comment by bitcrazed** [comment]
_From @zadjii-msft on April 24, 2017 15:39_

Gonna go out on a limb and say this has to do with the scroll margins, again.

MSFT:11647773 currently tracks what I think is this issue, though I'll add this to that bug to make sure they're the same. 

@warpdesign any chance that before you ran `npm install ...`, you had run `apt install ...`? I'm pretty sure that `apt` is a reliable repro for this behavior, but I don't know if `npm` is yet.

**Comment by bitcrazed** [comment]
_From @Po-wei on May 12, 2017 5:52_

I have the same scrolling problem, too. What's more, when I encounter this issue, typing "clear" would let me cannot scroll up(The scrolling bar was fixed on the top, and the previous information was gone.)

**Comment by bitcrazed** [comment]
_From @zadjii-msft on May 30, 2017 22:31_

Wadda ya know, I fixed this issue this morning. On it's way out to Insider's now :)

**Comment by bitcrazed** [comment]
_From @Po-wei on June 3, 2017 8:11_

@zadjii-msft When can i get this update from regular Windows Update?

**Comment by bitcrazed** [comment]
_From @zadjii-msft on June 5, 2017 16:16_

If you're not on Insiders, then I think the best I can tell you is Soon<sup>TM</sup>. It'll  come out with the Fall Creator's Update, but I don't know when that will officially be released.

**Comment by bitcrazed** [comment]
_From @MerkaST on December 6, 2017 23:17_

This appears to still happen with the Fall Creator's Update. I'm on build 16299.64 and running an `apt install` (or remove or autoremove, I'd assume all commands that use the progress bar) command that produces output longer than one window right after opening WSL will exhibit this behaviour, ie. have missing scrollback content.

**Comment by bitcrazed** [comment]
_From @zadjii-msft on December 8, 2017 17:32_

Hmmm. Okay so i think I get what's happening. Basically, the "scroll margins" that apt sets are at a fixed point in the buffer. So anything that would scrollback off of it, is just lost instead. 

The right way to do this is to probably instead shift the whole viewport down a line (including the buffer-relative margin settings), then scroll the contents of the margins up a line, so that the top line is off of the viewport, in the "scrollback".

Filing a new bug to take a look at this later this release cycle.

**Comment by zadjii-msft** [comment]
I just submitted a bug fix that should fix the issue of `apt install` output not getting moved into scrollback when it scrolls off the top of the viewport.

Should be in whatever the next official Windows release is called (2Fall2CreatorsUpdate)
