### ISSUE TITLE
Various Ctrl keyboard combinations aren't working (properly)

### ISSUE THREAD

**Issue by shlomme** [Microsoft/console#119]
* Your Windows build number:  10.0.16299.248

* What you're doing and what's happening:  Typing any of the following keyboard combinations doesn't work:

Alt-Backspace : Produces ^[^, which is Ctrl-Alt-Backspace
Ctrl-0, Ctrl-1, Ctrl-3-9, Ctrl--, Ctrl-/, Ctrl-:, Ctrl-=, Ctrl-` et al: produce no input
Ctrl-2: produces Ctrl-@

* What's wrong / what should be happening instead:

All key combinations should produce the expected output.

**Comment by zadjii-msft** [comment]
I think I need some more context here - how are you reading these keystrokes? From WSL? The Console API? 

I'm fairly certain none of those are keystrokes that can be represented in VT sequences, so if it's WSL then this is "by design"
