### ISSUE TITLE
Ansi Color like : [0;31m output that as char and still use cmdhost default color

### ISSUE THREAD

**Issue by tebeco** [Microsoft/console#123]
### Your Windows build number:  (Type `ver` at a Windows Command Prompt)
```
> ver
Microsoft Windows [Version 10.0.17110.1000]
```

### What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
* Just downloaded `Vault` for Windows x64, 
* unzipped
* opened a CMD ran `vault read` command :
```
>vault read
[0;31mNot enough arguments (expected 1, got 0)[0m
```
* Then opened WSL (Ubuntu)
```
>vault read
Not enough arguments (expected 1, got 0)
```
No more color char but still gray

* @ctolkien on Slack gave me few hint to fix it :
![image](https://user-images.githubusercontent.com/2266487/36871911-ebfb28ae-1da3-11e8-850f-1ff2db96cf84.png)
it was already `UNCHECKED` on both CMD and WSL (WSL was already on code page 65001)

```
>chcp
Active code page: 437

>chcp 65001
Active code page: 65001

>vault read
[0;31mNot enough arguments (expected 1, got 0)[0m
```

* I even started a new CMD to be sure
```
>vault read
[0;31mNot enough arguments (expected 1, got 0)[0m
```
### What's wrong / what should be happening instead:
[0;31 should be Red (hint: it is an error message)

**Comment by tebeco** [comment]
![image](https://user-images.githubusercontent.com/2266487/36873365-87c87a58-1da8-11e8-9c3d-5c262da020bc.png)

**Comment by parkovski** [comment]
That looks like vault doesn't set `ENABLE_VIRTUAL_TERMINAL_PROCESSING`.

**Comment by tebeco** [comment]
is that an env variable i can set in the cmdhost so it will enable it for vault ?
a PInvoke ? (so maybe a simple C# call)

 or it has to be done within vault ?

**Comment by parkovski** [comment]
Vault has to do that - it's either a bug in vault or whatever library they use to set up the console.

**Comment by jefferai** [comment]
@parkovski I think it's more like, how would we ever know that was necessary :-)

**Comment by jefferai** [comment]
@tebeco you can probably close this, we'll figure out something on the Go side until Windows handles this by default.

**Comment by tebeco** [comment]
yep thx for all the explanations
