### ISSUE TITLE
ColorTool: setting theme to solarized_dark affects Powershell and bad way

### ISSUE THREAD

**Issue by andriy-f** [Microsoft/console#127]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

**Microsoft Windows [Version 10.0.16299.248]**

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

`colortool.exe -d solarized_dark`

* What's wrong / what should be happening instead:

This is how `cd ..` looks in **Powershell** opened via **Open PowerShell window here** context menu before and after:

**Before**:
![image](https://user-images.githubusercontent.com/1040440/37028980-87238374-213e-11e8-8b26-0c3af5879974.png)

**After**:
![image](https://user-images.githubusercontent.com/1040440/37028911-576847be-213e-11e8-95aa-84a137ba7b5d.png)

**Comment by zadjii-msft** [comment]
That's to be expected (even if it's unintuitive).

You've set the default colors (in `HKCU/Console`) to be the solarized palette.

Then you've launched powershell, which loaded the defaults (solarized) and applied the powershell settings (in `HKCU\Console\<path_to_powershell.exe>`) on top of the defaults. Those powershell settings include changing "Dark Magenta" to Powershell Blue, Yellow to a light grey color, and changing the FG/BG to yellow on magenta (giving you the light grey on blue appearance of Powershell).

Unfortunately, yellow in the solarized scheme is a different grey color, and "bright black" (the color of the `..`) is just black, which gives you the terrible appearance there.

I'd just use colortool to change the powershell colors to something else (and save them with the property sheet) or just pick a different BG color for powershell.

**Comment by Tadimsky** [comment]
@zadjii-msft would it be possible to provide an example of how to do this?
This is what I have in my registry for PowerShell:
![image](https://user-images.githubusercontent.com/1149244/39684920-08bf5c90-5174-11e8-9ca9-14616ad28d80.png)

My big problem is if I run `cmd` and then start `powershell` inside that. Then the arguments names are invisible.
