### ISSUE TITLE
The installed font bedstead.otf can't be selected

### ISSUE THREAD

**Issue by mobluse** [Microsoft/console#156]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17128.1]

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
Trying to select a font, but it's not found.

* What's wrong / what should be happening instead:
It should be in the list.

The font that I wanted to use is Bedstead and it's installed:
http://bjh21.me.uk/bedstead/

It (bedstead.otf) works in WSLTTY and Tera Term.

**Comment by mobluse** [comment]
A workaround is to convert bedstead.otf to bedstead.ttf using https://everythingfonts.com/otf-to-ttf , and after installing that worked in WSL Ubuntu from Store.

**Comment by bitcrazed** [comment]
Thanks for reporting. Closing since we don't support OpenType at this time
