### ISSUE TITLE
Slow text buffer (native and WSL)

### ISSUE THREAD

**Issue by jkroepke** [Microsoft/console#165]
related: https://github.com/Microsoft/WSL/issues/2772

Hi there,

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17134.1]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

I have a HiDPI Desktop Environment on UHD with 125% Scale.

If I', using a termial multiplexer like tmux and I run commands which give huge text output, like dmesg (dmesg | wc -l -> 3951), the output lags totally.

On client systems like mac os or cygwin (on same machine), the output buffering is working fine.

Video: https://streamable.com/4e2i3

* What's wrong / what should be happening instead:

No lags.

**Comment by bitcrazed** [comment]
Thanks for the report. This is a known issue and is being fixed as I type! 

Closing as dupe for now.

Internal bug# 17258642
