### ISSUE TITLE
'mode' command no longer works within WSL

### ISSUE THREAD

**Issue by ax0** [Microsoft/console#168]
* Your Windows build number: Microsoft Windows [Version 10.0.17661.1001]

* What you're doing and what's happening:

> $ cmd.exe /c mode 100,40
> The screen cannot be set to the number of lines and columns specified.

* What's wrong / what should be happening instead:
The window should be appropriately resized after typing the above command.

On build 17134 I was able to resize the WSL console window using the above command (provided I did not call it from within a tmux session). However, while `mode` continues to work on the Command Prompt, once I drop into WSL (e.g. by executing `wsl.exe`), I get the above output. Running `mode.com` yields the same result.

**Comment by zadjii-msft** [comment]
Checked the fix in today. Should be out to insiders in roughly a month.

**Comment by zadjii-msft** [comment]
Hmm. I know I fixed this, but I must have broken it again. Looks like mode properly resizes the pseudoconsole, but it doesn't propagate to the terminal conhost window. I'll re-activate for the next milestone

**Comment by DHowett-MSFT** [comment]
This fix came out with Windows Insider Build 18334! Thanks!
