### ISSUE TITLE
The DEC special graphics character set shouldn't have control characters

### ISSUE THREAD

**Issue by j4james** [Microsoft/console#169]
* Your Windows build number:

Microsoft Windows [Version 10.0.16299.371]

* What you're doing and what's happening:

When I use the `ESC ( 0` escape sequence to enable the DEC special graphics character set, some of the characters don't seem to be correctly mapped. Specifically, code points \x62 to \x65, \x68, and \x69, which are meant to be glyphs representing the control characters (␉ ␌ ␍ ␊ ␤ ␋), and shouldn't be interpreted as the control characters themselves.

It's admittedly not particularly obvious from the mapping table provided in the VT100 manual, but I think it's a lot clearer in the [VT220 manual](https://vt100.net/dec/ek-vt220-rm-001.pdf#[{%22num%22%3A70%2C%22gen%22%3A0}%2C{%22name%22%3A%22XYZ%22}%2C0%2C648%2C0]), which lists both control characters and control character glyphs, so you can clearly see the difference.

As further confirmation, every Linux terminal emulator I've tested has displayed these code points as glyphs and not interpreted them as control characters. Here is a simple test case:

    printf "\e(0[b][c][d][e][h][i]\e(B\n"

The screenshot below shows the output from XTerm, Gnome Terminal, Konsole, and the Windows console.

![image](https://user-images.githubusercontent.com/4181424/39663472-eb1f6ada-506b-11e8-88bc-68593af5d1ec.png)

And note that the two characters that Windows does appear to display (with a replacement char) are still not correct. Those are being mapped to the "form feed" and "vertical tab" control characters, which Windows doesn't implement. If you had a font that supported those glyphs you'd see them as characters \x0C and \x0B (♀ and ♂) from code page 437.

* What's wrong / what should be happening instead:

When the DEC special graphics character set is enabled, code points \x62 to \x65, \x68, and \x69 should be displayed as glyphs and not interpreted as control characters.

**Comment by zadjii-msft** [comment]
Definitely my bad on reading the spec wrong. Good catch!

It took me long enough to find a font that even had those symbols, but fixing the bug was relatively straightforward. In code review now :)

**Comment by DHowett-MSFT** [comment]
Looks like this is fixed in the october 2018 update.

**Comment by jerch** [comment]
@j4james I am not quite sure if the change is the correct behavior - the manual you referred clearly states, that the graphics set only gets loaded into GR/GL? Which would skip the C0/C1 positions. Also the other charsets listed before in the manual show the control codes as well with kinda the same notation.

Following the parser suggested by VT100.net there seems to be no link between a selected charset and a different behavior/repr of C0 codes. Have not yet checked if DEC STD 070 has something more to tell here. Might have to find out the hard way, not sure if my old vt420 still works...
