### ISSUE TITLE
Printing to console at the same time as selecting text causes deadlock

### ISSUE THREAD

**Issue by LunarLambda** [Microsoft/console#185]
Microsoft Windows [Version 10.0.16299.431]
![2018-05-19_23-34-36](https://user-images.githubusercontent.com/38919842/40273263-622713d8-5bbd-11e8-900b-fe0162f94a15.gif)
Attempting to print text to the console and selecting text at the same time causes a deadlock.

**Comment by miniksa** [comment]
What is b? Which API is it calling?

**Comment by LunarLambda** [comment]
@miniksa basically while (true) puts("hi");

I also tested it with std::cout, and also WriteConsole directly.

**Comment by miniksa** [comment]
OK. Sometimes they back-end on different functions on our side. I'll whip up a little utility and try this out. Thanks.

**Comment by miniksa** [comment]
Hmmm, not happening for me on 17686. Let me go stand up a 16299 image and see if it happens.

**Comment by miniksa** [comment]
Not repro on 17718 (RS5 Insiders Build).
Not repro on 17134.1 (RS4 release).
Not repro on 16299.431 (RS3 release).

Please reactivate if you can provide the actual source code for "b" that makes this repro.

**Comment by LunarLambda** [comment]
Doesn't repro on my machine anymore
