### ISSUE TITLE
stdout/stderr buffer in PowerShell seems to override content on split panes in tmux.

### ISSUE THREAD

**Issue by toloveru** [Microsoft/console#187]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.431]

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
In WSL Bash, I opened tmux and split it up into 4 panes (2x2 configuration). Next, I executed powershell.exe in the top right window, which successfully brought me into a PowerShell. When executing "ls" some of the stdout (or whatever the equivalent in PowerShell is) is printed in the top left pane, where a completely unrelated SSH session to my Arch Linux laptop was ongoing. This seems to me like some of the content (seemingly the string "Mode    LastWriteTime   Length Name") is hardcoded to start at terminal window column 0 - rather than whatever tmux has decided it should start at.
It does however seem to disappear whenever I click on the top left pane, and show the running SSH session again.
![powershell](https://user-images.githubusercontent.com/19938179/40279226-e7bdb908-5c3e-11e8-90ba-19c35bc604ff.png)

* What's wrong / what should be happening instead:
The PowerShell pane should cooperate nicely with WSL Bash and its terminal window border allocations, instead of printing to another tmux pane that it shouldn't even be permitted access to.

**Comment by miniksa** [comment]
That's alright. Thank you for cleaning it up.

**Comment by zadjii-msft** [comment]
Oh this is a known issue with interop scenarios on April Creator's Update and earlier. Unless the application is just writing raw text, it'll act REALLY poorly when run on interop. 

Fortunately that's all fixed in newer builds! See #57 for details. Anything above 17618 will work like a charm :)

**Comment by toloveru** [comment]
@zadjii-msft That's great to hear. I will consider getting the Insider build in the meantime. Thanks for the clarification!
