### ISSUE TITLE
vbindiff background and border rendering broken

### ISSUE THREAD

**Issue by shoffmeister** [Microsoft/console#189]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17134.48]

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

vbindiff on unbuntu 18.04 rendering of its background and borders is broken.

To reproduce in general, 'sudo apt install vbindiff' on Ubuntu 18.04, then diff any two large binary files.

![image](https://user-images.githubusercontent.com/3868036/40419487-d3763058-5e85-11e8-95fc-e64ce08892e3.png)

Notice that the gray background missing in the top and middle; the blue background where no output was written. Notice also the badly formatted border / frame at the bottom of the window.

Note: Upon resizing the console window, the background gets redrawn correctly, but the frame at the bottom is still off.

* What's wrong / what should be happening instead:

KDE konsole (shown via vcvxsrv Windows X server) rendering from the same system:

![image](https://user-images.githubusercontent.com/3868036/40419426-9e988cbe-5e85-11e8-8b70-77650b1f004f.png)

**Comment by zadjii-msft** [comment]
Currious that resizing __fixes__ this problem, I'd expect resizing to actually cause this behavior.

This kinda reminds me of #70, I'll take a look. The bottom frame should definitely not look like that.

**Comment by zadjii-msft** [comment]
Actually it turns out this was the issue reported in #240.

Should be fixed and on it's way out to insiders now :)
