### ISSUE TITLE
Non-ASCII characters are garbled

### ISSUE THREAD

**Issue by vyv03354** [Microsoft/console#192]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.17672.1000

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
Displaying non-ASCII characters

* What's wrong / what should be happening instead:
Non-ASCII characters are garbled (See screenshot)

![image](https://user-images.githubusercontent.com/1146190/40454256-03896754-5f23-11e8-84e1-049f28871b88.png)

Expected result (with April 2018 Update):

![image](https://user-images.githubusercontent.com/1146190/40454197-c8942cd8-5f22-11e8-971d-6b29335704bb.png)

**Comment by mikemaccana** [comment]
Coming from https://github.com/PowerShell/PowerShell/issues/6931: similarly: I have a command line app that outputs warnings using ⚠ - this fails on pwsh 6.1 beta in current fast ring console.

Steps to reproduce
------------------

```powershell
echo ⚠
```

Expected behavior
-----------------

```none
⚠
```

Actual behavior
---------------

![image](https://user-images.githubusercontent.com/172594/40480627-fccb618c-5f46-11e8-9826-0f517c880234.png)


```
[?][?]
```

**Comment by zadjii-msft** [comment]
I think this is a known regression with a fix on the way up, @adiviness could you verify this is a dupe of that issue?

**Comment by vyv03354** [comment]
> What’s happening is that the width of the first character in a row is getting applied to all characters in the line when we draw.

It does not explain the result of the second line:
> 操可なロラまはッ` ァルし認さてまん。

Although the first character in this line is a full-width, only odd-numbered (1st, 3rd, 5th, ...) characters are drawn.
It should be:
> 操作可能なプログラムまたはバッチ ファイルとして認識されていません。

**Comment by adiviness** [comment]
That is a separate rendering bug that is due to a misunderstanding of how we store double width characters and subsequently render them. It has also been fixed and making its way out.

**Comment by vyv03354** [comment]
Fixed confirmed with build 17682. Thanks!

![image](https://user-images.githubusercontent.com/1146190/40981612-4e2649d8-6916-11e8-9c87-eb5c01e54c89.png)
