### ISSUE TITLE
solarized itermcolors don't correspond to the provided rgb values in the solarized repository

### ISSUE THREAD

**Issue by JackeJR** [Microsoft/console#20]
As the title suggests, the values by colortool using the solarized itermcolors don't correspond to that in the solarized repository. I created an ini to use the values from the solarized repos:

```
[table]
DARK_BLACK     = 0  , 43 , 54
DARK_BLUE      = 38 , 139, 210
DARK_GREEN     = 133, 153, 0
DARK_CYAN      = 42 , 161, 152
DARK_RED       = 220, 50 , 47
DARK_MAGENTA   = 211, 54 , 130
DARK_YELLOW    = 181, 137, 0
DARK_WHITE     = 238, 232, 213
BRIGHT_BLACK   = 7  , 54 , 66
BRIGHT_BLUE    = 101, 123, 131
BRIGHT_GREEN   = 147, 161, 161
BRIGHT_CYAN    = 131, 148, 150
BRIGHT_RED     = 203, 75 , 22
BRIGHT_MAGENTA = 108, 113, 196
BRIGHT_YELLOW  = 88 , 110, 117
BRIGHT_WHITE   = 253, 246, 227

[info]
name   = solarized-dark
author = JackeJR
```

**Comment by Nacimota** [comment]
I'm looking at the iTerm2 scheme file for the dark theme in the official Solarized repo (located [here](https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized)) and the only difference between it and the file included in this repo is the inclusion of the license, copyright notice, etc. so I imagine that's where those colours came from. It hasn't been updated in 6 years so if the colours are out of date it might be worth raising an issue over there as well if there isn't one already (sadly, the repo seems mostly abandoned).

**Comment by zadjii-msft** [comment]
I concur with @Nacimota. @JackeJR which colors in particular do you think are wrong?

**Comment by craigloewenms** [comment]
@JackeJR solarized_dark was is the same as the copy in the [solarized repo](https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized) posted by @Nacimota . 

If you use solarized_light as is from that same repo you'll find that it doesn't map correctly to the Windows Console colors. The colors for solarized_light were derived from his website [here](http://ethanschoonover.com/solarized#the-values) where the specified values were inputted to the appropriate locations to make the light scheme.

Please let us know if there are any particular colors you think aren't correct!

**Comment by JackeJR** [comment]
Ok, I will just use the first colour as an example.
If I do `colortool -b solarized_dark.itermcolors` , for the first colour I get `R 0, G 39, B 49` when it should `R 0, G 43, 54`. Looking at the `itermcolors` file I see the below:
```
<key>Ansi 0 Color</key>
	<dict>
		<key>Blue Component</key>
		<real>0.19370138645172119</real>
		<key>Green Component</key>
		<real>0.15575926005840302</real>
		<key>Red Component</key>
		<real>0.0</real>
</dict>
```

Hazarding a guess is that `RGB` values are expressed as a proportion of 255, rounded down. I did not investigate further beyond that as it was just easier to write out the `ini` file for the correct values.

**Comment by JackeJR** [comment]
Just a little more digging from [HERE](https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized)

> The colors in iTerm2 currently cannot be device colors. They are baked in as generic rgb (which, despite the name, is an actual, specific color space from Apple and is used as a default just like other systems use sRGB as a default). I've switch Solarized Apple Color Picker palettes to use tagged colors by default, so for the most part iTerm2 will match up with other apps where you use Color Picker swatches.

Could the difference arise from the different default colorspaces in Mac OS vs Windows? I am not versed enough in Mac to say if this is the case.

**Comment by craigloewenms** [comment]
I believe the difference is arising from the fact that the [repository's iterm solarized_dark theme](https://github.com/altercation/solarized/blob/master/iterm2-colors-solarized/Solarized%20Dark.itermcolors) is out of date as @Nacimota mentioned, and it doesn't have the same values as [the values on the solarized website](http://ethanschoonover.com/solarized#the-values). I'll investigate on what the team's action plan should be with regards to this discrepancy and get back to you!

**Comment by craigloewenms** [comment]
After doing some investigating, it seems that this is already an [open issue](https://github.com/altercation/solarized/issues/257) on the solarized github repo (although it is quite old).

As well [other repositories use the Iterm scheme straight from the solarized repo](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/schemes/Solarized%20Dark.itermcolors). 

This repository should be using the official released iterm color scheme that is on the [solarized github page](https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized). Once that scheme is updated we can update the scheme on this repository.

You've already made your own theme to reflect the colors that solarized has on their website, which would be my only recommendation.

I'm closing the issue as currently no further action needs to be taken on our part. Thanks for bringing this to our attention!

**Comment by leo60228** [comment]
For future reference, @JackeJR's theme is also incorrect (as far as I can tell). Here's a .ini based on the colors in altercation/solarized's xresources file:

```
[table]
DARK_BLACK     = 7,54,66
DARK_BLUE      = 220,50,47
DARK_GREEN     = 133,153,0
DARK_CYAN      = 181,137,0
DARK_RED       = 38,139,210
DARK_MAGENTA   = 211,54,130
DARK_YELLOW    = 42,161,152
DARK_WHITE     = 238,232,213
BRIGHT_BLACK   = 0,43,54
BRIGHT_BLUE    = 203,75,22
BRIGHT_GREEN   = 88,110,117
BRIGHT_CYAN    = 101,123,131
BRIGHT_RED     = 131,148,150
BRIGHT_MAGENTA = 108,113,196
BRIGHT_YELLOW  = 147,161,161
BRIGHT_WHITE   = 253,246,227

[info]
name   = solarized_dark
author = leo60228
```

Do note when using this that the correct text color is the 13th from the left, or color 12 (for programs that use ANSI color codes).
