### ISSUE TITLE
Missing cursor

### ISSUE THREAD

**Issue by parkovski** [Microsoft/console#200]
There is no cursor when I open the console window. I only started seeing this in the last insider build, and it's still here in today's (17682).

This happens _most_ of the time, but not all the time. No idea why that could be 😞 .

One more edit - when opening a new pwsh.exe in tmux, the cursor is initially in a seemingly random place, but when I start typing, it stays one cell ahead of the text. When I press escape (I'm using vi edit mode in PSReadLine), it jumps to the second cell in the first row, and jumps back to one ahead when typing. Resizing the window fixes the glitches. Putting that here since it seems like that could be the same issue showing up differently through the interop PTY. It also blinks very quickly or not at all in tmux.

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
17682

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
When I open a console (tried PowerShell, cmd and zsh; all are affected), the window expands by (seems like) one row and one column, and there is no cursor. No escape sequence I've tried will bring the cursor back. However:
  - Opening Windows vim (console API secondary buffer) has a cursor, and after quitting it the cursor is permanently back.
  - Opening Linux vim (ANSI secondary buffer) has a cursor, but after quitting it the cursor is gone again.

I'm pretty sure this is not the same as the black cursor issue - moving the "cursor" works, but none of the letters ever gets covered - the screen always looks the same.

* What's wrong / what should be happening instead:
There should always be a cursor...

**Comment by miniksa** [comment]
This is fixed in Insiders 17683 and higher. It was MSFT: 17369318
