### ISSUE TITLE
Can't change cursor in secondary buffer

### ISSUE THREAD

**Issue by parkovski** [Microsoft/console#201]
Since I'm doing all my secondary buffer issues... Using the cursor change sequences in Windows vim doesn't work. They do work in Linux vim and in the regular PowerShell prompt (Windows).

Just realized this may just be vim not setting `ENABLE_VIRTUAL_TERMINAL_INPUT`. Not sure though, since this is a printed sequence, and true color works - do the cursor escapes need the input or output mode set?

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
17682

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
Execute the following in vim (in vimrc or otherwise):

```
let &t_SI = "\<Esc>[5 q"
let &t_SR = "\<Esc>[3 q"
let &t_EI = "\<Esc>[1 q"
```

Now switch between normal and insert mode. Instead of the cursor being set, you'll see ` [5 q` / etc printed to the screen.

* What's wrong / what should be happening instead:
The escapes should change the cursor, not write to the screen.

**Comment by DHowett-MSFT** [comment]
Hey @parkovski,
I'm having trouble reproducing this on the latest insider builds. I don't have an exact timeline, but I do know that we did some work on propagating state to the alternate buffer.
I'm going to mark this `fixed-in-insiders` and close it. If it's still an issue, please let us know!
