### ISSUE TITLE
Console seemingly having problems with many-colored text in one line

### ISSUE THREAD

**Issue by JMoVS** [Microsoft/console#203]
* Your Windows build number:  10.0.17134.81

* What you're doing and what's happening: I was using @nwronski's [batch-transcode-video](https://github.com/nwronski/batch-transcode-video) on Ubuntu bash/cmd.exe in Windows 10. I noticed that the console seems to have problems with colours somehow. This is how it looked for me:
![unbenannt](https://user-images.githubusercontent.com/7354506/40890811-3d1cab6e-677c-11e8-884d-1cf4b41f210c.JPG)

Compare that to the screenshot of the project and the behaviour on linux/Mac OS, where the status line actually displays status:
![with-status](https://cloud.githubusercontent.com/assets/5528249/11022434/025d9d4a-862d-11e5-8b0c-4134e7edd0d7.png)

* What's wrong / what should be happening instead:
No matter if I opened "Ubuntu Bash" from the start menu or ran "bash -c command" in cmd.exe, it should display the status line.

**Comment by zadjii-msft** [comment]
Is this still affecting you? Should we investigate or can we close this issue?

**Comment by JMoVS** [comment]
I'm unable to test it myself currently and will check back the next time I'm at my Dad's home. There is another issue that probably exists somewhere already where the text ouput to the windows shell is really really slow in performance but this is unrelated to this issue. I will reopen this issue if I find that it is indeed affecting me. Thank you for your heads-up!
