### ISSUE TITLE
Block  or underline cursor setting

### ISSUE THREAD

**Issue by mriffey** [Microsoft/console#205]
I dont see a block cursor style setting in the code, nor have numerous experiments with HKCU/Console/CursorType resulted in regaining a cursor. 

I am on preview 17682 prerelease 180525 and havent found a way to have an underline or block cursor. 

VER: [Version 10.0.17682.1000]

Thanks, Mark

**Comment by zadjii-msft** [comment]
How are you opening the console? Is is a shortcut, like win+x, c? 

The problem here is that the CursorColor is missing from the shortcut. See #193. You should be able to restore it by setting CursorColor to 0xffffffff in the registry, though I'm not positive that will work to fix shortcuts as well.

Fix was checked in earlier today.

**Comment by mriffey** [comment]
I use the console a lot, so it's pinned to the taskbar, however unpinning it and repinning it did not correct the issue. I also started it from start, typing con, then clicking the search hit - same result. I even tried starting it directly from \system32\cmd.exe, but the cursorcolor registry change didnt have an impact.

**Comment by mriffey** [comment]
After reading #193, I renamed CursorColor and got my block cursor back. Thanks to the tip.

**Comment by zadjii-msft** [comment]
Does this repro with powershell//wsl/bash/<distro of choice>, or only cmd?

Does it repro with `start cmd`?

The default cursor is (CursorType, CursorColor) = (0, 0xffffffff). Did you set the registry in `HKCU\Console`, `HKCU\Console\%SystemRoot%_system32_cmd.exe` or both? Anything in the cmd.exe one will override the one in the Console root.

**Comment by zadjii-msft** [comment]
Well I'm glad that fixed it for you!

**Comment by mriffey** [comment]
Actually, it still doesnt work from a shortcut, but i suspect that might be related to your check-in. Works great if I start cmd.exe from system32, so ill do that until the next insider release comes out.

**Comment by zadjii-msft** [comment]
It'll probably be a few Insider's releases before this gets out, unfortunately. It takes a while for code we check in to bubble up through the code tree.

**Comment by mriffey** [comment]
Here's a screenshot of system32/cmd vs pin/shortcut and the registry setting Im using. Hope it helps. https://cl.ly/433J1j2p2E0z/[346f34fffee0a8bee7c956f46c6350ad]_Image%202018-06-08%20at%2011.19.34%20AM.png
