### ISSUE TITLE
Console loses color when when spawning a new command prompt

### ISSUE THREAD

**Issue by ethanhs** [Microsoft/console#207]
I'm pretty sure this is a bug, but it might be a feature request. (Also I recognize this is probably low priority).

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.17686.1003]
Though I will note that it has been this way forever.

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

```
$ cargo build
     <green>Finished</green> dev [unoptimized + debuginfo] target(s) in 0.30s
$ cmd
Spawns new shell, etc, but the colorful output from cargo build is now gone!
```
Example:
![2018-06-13_15-02-38](https://user-images.githubusercontent.com/9504279/41380841-e35968a0-6f1a-11e8-8afc-7f126103d626.gif)

* What's wrong / what should be happening instead:

It seems the color information is lost somewhere, and everything goes back to being black and white :(

**Comment by Ansuel** [comment]
this also happen in a powershell console when calling cmd command...

**Comment by DHowett-MSFT** [comment]
A fix for this shipped in 19H1 Insider Build 18312. Try it out!

**Comment by ethanhs** [comment]
I can confirm that the fix works. Thank you and everyone on the console team for your work! 🎉
