### ISSUE TITLE
Glitch in menuconfig

### ISSUE THREAD

**Issue by Ansuel** [Microsoft/console#208]
Microsoft Windows [Versione 10.0.17692.1000]

![ezgif-5-6159a78bf7](https://user-images.githubusercontent.com/20289090/41499584-a62f2d7e-7182-11e8-8b31-9b6740110a57.gif)

**Comment by zadjii-msft** [comment]
There are two issues here:

 1. buffer changes to black when scrolling
 2. Horizontal lines don't work/display

1 is a bug that's already fixed internally. 

2 is already being tracked by #194

**Comment by Ansuel** [comment]
@zadjii-msft 

the bug 1 is still present in this new insider build... tought it was fixed internally...
