### ISSUE TITLE
Arrows ignored by bash when it started in ConEmu

### ISSUE THREAD

**Issue by fabioformosa** [Microsoft/console#209]
Regarding your last [comment](https://github.com/Microsoft/WSL/issues/111#issuecomment-391157245) about this [issue](https://github.com/Microsoft/WSL/issues/111),
Could you provide some details to get/install the fix, please? thank you.

**Comment by miniksa** [comment]
Get the most recent release of Windows 10 April 2018 Update (1803) or be on a recent Windows Insiders build.

It looks like this has been fixed in all public Windows 10 builds created after October 11th, 2017.
