### ISSUE TITLE
Gorm database logs not rendering colors properly unless ansicon is installed

### ISSUE THREAD

**Issue by benfaught** [Microsoft/console#211]
My system: 
![mysys](https://user-images.githubusercontent.com/24580002/41799730-2f78ffa6-7638-11e8-8790-e1c1d300dc13.PNG)

My Windows build number: 
* Microsoft Windows [Version 10.0.17134.112]

I'm running golang server and printing database logs to console using gorm.
specifically using this method: https://godoc.org/github.com/jinzhu/gorm#DB.LogMode

Here's the command and output (without ansicon installed):
![woansi](https://user-images.githubusercontent.com/24580002/41799401-02b90476-7637-11e8-9df4-cebdada79756.PNG)

Here's the command and output (**WITH** ansicon installed):
![withansi](https://user-images.githubusercontent.com/24580002/41799428-29821f3e-7637-11e8-8a55-9c54c5cdfa12.PNG)

* Here is the what I have installed to make the color output of the logs render correctly:
https://github.com/adoxa/ansicon

* Shouldn't the colors render correctly in the console without ansicon installed?

* FYI, I get the same results in both cmd & powershell.
Here is a link to gorm's logger, written in Go (shows the formatting used):
https://github.com/jinzhu/gorm/blob/master/logger.go

**Comment by j4james** [comment]
The ANSI/VT escape sequences are not enabled by default in the Windows console. You need to set a registry key (`HKEY_CURRENT_USER\Console\VirtualTerminalLevel`) to turn on that functionality. I'm not sure if it is officially documented anyway, but it was explained in the comments of one of the WSL issues. See [here](https://github.com/Microsoft/WSL/issues/1173#issuecomment-370665039).

**Comment by benfaught** [comment]
**Yes!**  Worked Perfectly.  Look at those beautiful colorful logs 😍 **Thank You!**
![beautylogs](https://user-images.githubusercontent.com/24580002/42129927-d07a2a40-7c98-11e8-88dd-bc0fa803d153.PNG)

**Comment by benfaught** [comment]
Perfect.  Thank you

Ben

**Comment by zadjii-msft** [comment]
For the record, the reg key is a bit of a hack, (and honestly I forgot it was there). Applications on windows that want to enable the VT support should be using SetConsoleMode with the ENABLE_VIRTUAL_TERMINAL_PROCESSING flag, so that all users of the application will get the same behavior.

**Comment by j4james** [comment]
@zadjii-msft If you're writing a cross-platform app, though, it's a bit disappointing being told that you have to add platform-specific API calls to your code just to get functionality that works out of the box in other operating systems (including older versions of Windows back in the ansi,sys days). Personally I would just have stuck with ansicon if that registry option wasn't available, so I hope you aren't planning on removing it.

**Comment by zadjii-msft** [comment]
Aye, but unfortunately our ultimate loyalty is to supporting backwards compat, and for whatever reason we can't just enable it by default :(.

However, you can be sure that means we're not pulling the reg key either :)
