### ISSUE TITLE
Most of screen goes blank in post spring update beta builds

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/console#212]
* What you're doing and what's happening: 

When using some sort of *nix program that buffers pages/content, in particular neovim but also other apps, a significant portion of the screen will go blank (i.e. from top of screen to line _n_) and requires a ctrl^l to restore content. Does not happen under putty.

This is easily (but not deterministically) replicated by playing around with neovim 0.3 with `set termguicolors` on and `TERM=xterm-256color` (the default).

* Your Windows build number: *see below*

Does not happen under 17134. Did not happen in the first insider preview build that went out to fast track (not skip ahead) insiders post the 17134 release. Happened in 17672. Still happening in 17704.

* What's wrong / what should be happening instead: screen shouldn't lose text.

**Comment by zadjii-msft** [comment]
This is #210
