### ISSUE TITLE
When scrolling vim, text is not displayed properly.

### ISSUE THREAD

**Issue by toloveru** [Microsoft/console#213]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Windows Home Insider Preview build 17704.rs_prerelease.180623-1611 (fast ring)

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
When using vim - both on local or SSH remotes and on both Ubuntu 16.04 as well as 18.04 - when scrolling only the last few lines are shown, while the others aren't rendered. When activating mouse support using `:set mouse=a` and scrolling down a file, only the last 3 lines are rendered. When using the arrow keys to do so, only the last 1 line is shown. Due to this happening in all the distributions that I've tested so far as well as remotes running different ones, I believe that this is an issue in conhost. Also this doesn't happen in my laptop which runs Arch Mate and on which I'm using Terminology, further supporting that the issue may lie in conhost. Lastly I've tested this issue in SUSE Leap 42 on WSL where the issue is occurring as well.
One thing that I found noteworthy is that this issue doesn't seem to happen in vi while in SSH sessions to other hosts - on WSL Ubuntu it seems to be linked to vim without any straightforward option to install vi. The aforementioned SSH remotes are running Arch Linux with their default vimrc. Another peculiarity is that Ctrl-L (which redraws the shell) makes the rendering happen correctly. Needless to say, having to do that every time when scrolling is a PITA.

* What's wrong / what should be happening instead:
The text should be rendered properly and be kept like that during scrolling.

**Comment by zadjii-msft** [comment]
This is #210. The fix is on the way out to Insiders.

**Comment by toloveru** [comment]
Thanks for the quick follow-up, much appreciated. My apologies for not thoroughly checking the existing issues for this.
