### ISSUE TITLE
Shift key on on-screen keyboard registers null character on WSL

### ISSUE THREAD

**Issue by ax0** [Microsoft/console#215]
* Your Windows build number: Microsoft Windows [Version 10.0.17134.137]

* What you're doing and what's happening: Using the on-screen keyboard in tablet mode to interact with WSL (via the Command Prompt). Certain applications react strangely after the shift key has been pressed.

* What's wrong / what should be happening instead: Pressing the shift key seems to register the null character, which interferes with key bindings in different applications (e.g. Emacs and Mutt). To see this, run 'showkey -a' and press the shift key on the on-screen keyboard:

```
$ showkey -a

Press any keys - Ctrl-D will terminate this program

^@        0 0000 0x00
```
AltGr registers the null character as well on those keyboard layouts that have it.

**Comment by DHowett-MSFT** [comment]
Looking into this a little bit, it looks like the virtual keyboard and physical keyboard generate different events for Shift (quelle surprise!)

```
Field     | OSK Value | Phys. Keyboard Value
---------------------------------------------------------
KeyDown   | TRUE      | TRUE
Repeat    | 1         | 1
KeyCode   | 0x10      | 0x10
ScanCode  | *0x0*     | *0x2a*
Character | 0         | 0
Modifiers | 0x10      | 0x10
```

So far, this appears to be the only difference between a "good" and "evil" shift keypress.

**Comment by ns740** [comment]
not sure how you generate this table (without a virtual console) but just want to confirm you are looking at the tablet "touch keyboard" *NOT* the osk.exe touch keyboard.   (thanks for checking this thing!)

**Comment by DHowett-MSFT** [comment]
Yep, this is the tablet "touch keyboard."

**Comment by DHowett-MSFT** [comment]
Good news! We traced this back to a touch keyboard bug, and that team is taking it on as a bugfix.

**Comment by ns740** [comment]
brilliant.
thanks!

**Comment by miniksa** [comment]
@DHowett-MSFT, do you have the work item ID for this one?

**Comment by DHowett-MSFT** [comment]
That’ll be MSFT:20098298. It’s fixed, but not yet released.

**Comment by DHowett-MSFT** [comment]
This is finally fixed as of Insider's Build 18334. Thanks for the report, and for the patience!
