### ISSUE TITLE
Conhost doesn't render characters that aren't present in the primary font.

### ISSUE THREAD

**Issue by toloveru** [Microsoft/console#219]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
10.0.17704.1000 (Insider Preview Fast ring)

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
Generally I use WSL and conhost a lot to interface with my Linux servers.. and its experience has become more and more delighting over time, which I really appreciate. One particular issue in the rendering however is that even though I have installed a Powerline patched font that supports all the extra required glyphs, characters like exit status (✔) or box drawing characters (╭╰) do not display correctly, instead they're just these boxes denoting unrecognized characters in the console. In Chrome Canary on the Windows system itself, they're displayed just fine. An arrow key, and some rounded rectangular-shaped glyphs for drawing. Perfect! So it seems like the fonts are installed and are able to render these characters, but the conhost seems to only rely on its primary font. I don't think that these characters are in Monofur for Powerline directly.
The characters to denote git directory (like  which for some reason in Chrome renders as an up arrow.. strange) do render correctly though, and the proper Powerline fonts have been installed (which makes this related to fonts such as in [this issue](https://github.com/Microsoft/WSL/issues/881), but - hopefully - not user error (? Not sure if WSL was able to render Powerline at the time.. probably not but the font used is unclear) as has happened there). Anyway, I really hope that this isn't a duplicate of some issue that I haven't been able to check though.
From tests in PowerShell (where the default Consolas was still set) I was able to confirm that this font supports the aforementioned glyphs but not the Powerline ones. This should support the "conhost doesn't look in other fonts, even though the glyphs are present there" issue.

* What's wrong / what should be happening instead:
As a workaround I _could_ fork and edit this Monofur font to include the glyphs that I need, but that'd be a royal pain in the ass and I really don't want to do it. The only real universal and long-term solution would be for conhost to look for presence of glyphs in other fonts whenever it isn't found in the primary font.

![wsl](https://user-images.githubusercontent.com/19938179/42485212-fd0a1c5e-83f6-11e8-8100-88b70909000e.png)
![powershell](https://user-images.githubusercontent.com/19938179/42485473-07645fe2-83f8-11e8-8ca2-c0317908ebf3.png)

**Comment by DarthSpock** [comment]
Related to or possibly dupe of #169.

**Comment by zadjii-msft** [comment]
Ah, no #169 is kinda different (and already on it's way out to insiders)

This is a dupe of #190, we need to support font fallback

**Comment by DarthSpock** [comment]
Ah ok, I saw about the glyphs and thought that. I did consider that issue to be the other possibility but couldn't recall the issue number.
