### ISSUE TITLE
ColorTool does not work on Linux distros

### ISSUE THREAD

**Issue by wigster** [Microsoft/console#22]
Not sure this is what I should be doing, but the bash window for WSL does not get modified using this tool, so I default to an ugly color selection.

**Comment by zadjii-msft** [comment]
This is a known limitation unfortunately. @benhillis can comment more on the interop portion of it. Unfortunately there's not a great solution for this use case yet :/

**Comment by thisguychris** [comment]
this is the first thing I tried when I used this tool.

One workaround is open command prompt which has the colors you have and just type bash, and there you go, you get the colors you set.

**Comment by Falcury** [comment]
The changes in #50 are allowing me to set the colors from within bash. Although the color scheme is not saved permanently, you could add this to `~/.bashrc`, so that the colors will be silently set at launch:
```
pushd /path/to/ColorTool &> /dev/null
./colortool.exe -q -x <schemename>
popd &> /dev/null
```
Right-clicking the title bar, and clicking OK in the Properties dialog also seems to make the color scheme permanent. (Although you might have to do that separately for the case where you launch via the start menu, and the case where you launch bash.exe from an explorer window address bar.)

**Comment by rofrol** [comment]
@Falcury It does not work for me.

```bash
[rofrol@DESKTOP-NBALJ88 ~]$ pushd ~/rofrol/installed/colortool/ &> /dev/null
[rofrol@DESKTOP-NBALJ88 ~/rofrol/installed/colortool]$ ./colortool.exe -s

Unhandled Exception: System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.get_WindowWidth()
   at ColorTool.Program.PrintSchemes()
   at ColorTool.Program.Main(String[] args)
```

**Comment by zadjii-msft** [comment]
I'm going to close this issue, because as @Falcury mentioned, #50 fixed this. 

Fixing `-s` on WSL will take another PR - I filed #312 to track that.

**Comment by buncismamen** [comment]
for people who stumble to this issue when trying to applying colorbox in WSL

my steps is here

download colortool.zip
extract it somewhere
open the exctracted folder inside WSL bash
run the command with -x options
mine is `/mnt//e/ColorTool$ ./ColorTool.exe -x solarized_dark`
your wsl bash should change color according to your colorscheme

to make it permanent right click your wsl bash window
click properties
then in properties window just click ok
it should make it permanent

**Comment by rofrol** [comment]
@buncismamen Your solution does not worked for me. This worked when providing full path to `itermcolors` file:

`/mnt/c/Users/roman/installed/ColorTool$ ./ColorTool.exe -x schemes/solarized_light.itermcolors`
