### ISSUE TITLE
Rendering in vim broken

### ISSUE THREAD

**Issue by anovak10** [Microsoft/console#220]
Insider Preview, Build 17692, prerelase_fit 180625-1624

Last update broke console rendering for me when using WSL and vim. Initially it works, but after navigating down the end of the page, text disappears.

Issue exists in the regular ubuntu app, ubuntu 18.04 and with different terminals.

**Comment by zadjii-msft** [comment]
There are a bunch of issues that are all the same thing as you describe:
the root issue: #210
Dupes:#212 #213 #214 

Please search before filing bugs. This issue is already fixed internally and on it's way out
