### ISSUE TITLE
Pasting into bash shell P:1234 pastes /mnt/p/1234

### ISSUE THREAD

**Issue by ahmadalli** [Microsoft/console#223]
* Your Windows build number:  10.0.17134.165

* What you're doing and what's happening: paste `P:1234` into an empty bash shell

* What's wrong / what should be happening instead: I need `P:1234` not ` /mnt/p1234` since `P:1234` is not a path in my system.

**Comment by DHowett-MSFT** [comment]
This sounds like a ConEmu feature. Are you using ConEmu?

**Comment by ahmadalli** [comment]
yes. sorry I didn't check that first :)
