### ISSUE TITLE
Command Prompt has white cursor whereas Bash (WSL) have black cursor. 

### ISSUE THREAD

**Issue by shakeelansari63** [Microsoft/console#225]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
> Microsoft Windows [Version 10.0.17711.1000]

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
> When I open Command Prompt (cmd.exe), the prompt opens with White cursor, But when I open Bash (bash.exe) it opens with Black cursor which is almost impossible to see.

* What's wrong / what should be happening instead:
> The black cursor on Bash make it very difficult to see the cursor. If you can add an option to change cursor color that would be very helpful.

![CMD Screenshot](https://github.com/shakeelansari63/Other/blob/master/cmd.png)
![BASH Screenshot](https://github.com/shakeelansari63/Other/blob/master/bash.png)

**Comment by keichinger** [comment]
Just a wild guess: Are you sure that you didn't - by accident - make your cursor black due to your custom prompt styling?

**Comment by zadjii-msft** [comment]
Okay there's a ton of dupes of this issue floating around, but long story short we've fixed the issue that caused this to regress, but if you've already regressed, you might be stuck with bad settings populated in your shortcut. This will go back to normal in a future insider's flight, without cursor color persisting from session to session, until we can get a UI ready for it.
