### ISSUE TITLE
Zoom In and Out not possible 

### ISSUE THREAD

**Issue by liszca** [Microsoft/console#227]
Hi,
working on Hi resolution displays can be quiet painful without being able to zoom in.

Doing so with CTRL + Mousewheel and CTRL + "+"/ "-" should be possible.

Greetings
filip

**Comment by zadjii-msft** [comment]
Already on the backlog :)

**Comment by miniksa** [comment]
We did this as MSFT:19283836 on the mouse wheel. We didn't do the keys because we didn't want to deal with interrupting other things that might be using those keys at this time.

It's in Insiders 18272+.
