### ISSUE TITLE
Case sensitive folders breaks builds!

### ISSUE THREAD

**Issue by bitcrazed** [Microsoft/console#238]
## The problem
When building projects under this repo, if any of the folders are case sensitive, errors during build may be reported, e.g.: 

```
c1xx : fatal error C1083: Cannot open source file: 'stdafx.cpp': No such file or directory [C:\dev\microsoft\console\samples\ConPTY\EchoCon\EchoCon\Ech
oCon.vcxproj]
```

## Workaround
From _**an elevated PowerShell instance**_, disable folder case sensitivity using `fsutil.exe` against each of the folders in this repo:

``` powershell
ls -Path .\console\ -Directory -Recurse | %{fsutil file setCaseSensitiveInfo $_.fullname disable}
```

**Comment by zadjii-msft** [comment]
As discussed offline, this is an issue with MsBuild and case-sensitive directories/projects. Because this isn't really specific to this repo or the console, we're closing this issue as an external issue that should be brought up with the msbuild team.
