### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SCREAM2017** [Microsoft/console#239]
```
scream@ADWAA:/mnt/c/users/ad/desktop/t/compat-wireless-2010-09-01$ sudo make load
/sbin/modprobe: invalid option -- 'l'
/sbin/modprobe: invalid option -- 'l'
Stoping bluetooth service..
./scripts/unload.sh: line 35: /etc/init.d/bluetooth: No such file or directory
./scripts/unload.sh: line 36: /etc/init.d/bluetooth: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
grep: /proc/modules: No such file or directory
/sbin/modprobe: invalid option -- 'l'
/sbin/modprobe: invalid option -- 'l'
Loading ipw2100...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module ipw2100 not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading ipw2200...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module ipw2200 not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading libertas_cs...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module libertas_cs not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading usb8xxx...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module usb8xxx not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading p54pci...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module p54pci not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading p54usb...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module p54usb not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading adm8211...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module adm8211 not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading zd1211rw...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module zd1211rw not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading rtl8180...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module rtl8180 not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading rtl8187...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module rtl8187 not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading p54pci...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module p54pci not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading p54usb...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module p54usb not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading iwl3945...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module iwl3945 not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading iwlagn...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module iwlagn not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading ath...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module ath not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading ar9170usb...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module ar9170usb not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading rtl8180...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module rtl8180 not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading rtl8187...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module rtl8187 not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading rt2400pci...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module rt2400pci not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading rt2500pci...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module rt2500pci not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading rt61pci...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module rt61pci not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading rt2500usb...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module rt2500usb not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading rt73usb...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module rt73usb not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading rndis_wlan...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module rndis_wlan not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading at76_usb...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module at76_usb not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading mwl8k...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module mwl8k not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading mac80211_hwsim...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module mac80211_hwsim not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading at76c50x_usb...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module at76c50x_usb not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading bluetooth...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module bluetooth not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading btusb...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module btusb not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading l2cap...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module l2cap not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading sco...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module sco not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading hidp...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module hidp not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading rfcomm...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module rfcomm not found in directory /lib/modules/4.4.0-17134-Microsoft
Loading bnep...
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
modprobe: FATAL: Module bnep not found in directory /lib/modules/4.4.0-17134-Microsoft
./scripts/load.sh: line 21: athload: command not found
./scripts/load.sh: line 23: b43load: command not found
Starting bluetooth service..
./scripts/load.sh: line 25: /etc/init.d/bluetooth: No such file or directory
./scripts/load.sh: line 26: /etc/init.d/bluetooth: No such file or directory
make: *** [Makefile:350: load] Error 127
scream@ADWAA:/mnt/c/users/ad/desktop/t/compat-wireless-2010-09-01$
```

How to fix this ؟!

This [compat-wireless-2010-09-01] was loaded because the alpha device is not working in WSL

**Comment by zadjii-msft** [comment]
This doesn't look like it's a console issue at all.

If this is a issue with WSL not working, then please file it on [Microsoft/WSL](https://github.com/Microsoft/WSL).

**Comment by Secret-Coder1** [comment]
> ```
> scream@ADWAA:/mnt/c/users/ad/desktop/t/compat-wireless-2010-09-01$ sudo make load
> /sbin/modprobe: invalid option -- 'l'
> /sbin/modprobe: invalid option -- 'l'
> Stoping bluetooth service..
> ./scripts/unload.sh: line 35: /etc/init.d/bluetooth: No such file or directory
> ./scripts/unload.sh: line 36: /etc/init.d/bluetooth: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> grep: /proc/modules: No such file or directory
> /sbin/modprobe: invalid option -- 'l'
> /sbin/modprobe: invalid option -- 'l'
> Loading ipw2100...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module ipw2100 not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading ipw2200...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module ipw2200 not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading libertas_cs...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module libertas_cs not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading usb8xxx...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module usb8xxx not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading p54pci...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module p54pci not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading p54usb...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module p54usb not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading adm8211...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module adm8211 not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading zd1211rw...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module zd1211rw not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading rtl8180...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module rtl8180 not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading rtl8187...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module rtl8187 not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading p54pci...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module p54pci not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading p54usb...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module p54usb not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading iwl3945...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module iwl3945 not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading iwlagn...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module iwlagn not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading ath...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module ath not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading ar9170usb...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module ar9170usb not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading rtl8180...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module rtl8180 not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading rtl8187...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module rtl8187 not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading rt2400pci...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module rt2400pci not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading rt2500pci...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module rt2500pci not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading rt61pci...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module rt61pci not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading rt2500usb...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module rt2500usb not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading rt73usb...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module rt73usb not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading rndis_wlan...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module rndis_wlan not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading at76_usb...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module at76_usb not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading mwl8k...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module mwl8k not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading mac80211_hwsim...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module mac80211_hwsim not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading at76c50x_usb...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module at76c50x_usb not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading bluetooth...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module bluetooth not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading btusb...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module btusb not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading l2cap...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module l2cap not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading sco...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module sco not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading hidp...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module hidp not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading rfcomm...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module rfcomm not found in directory /lib/modules/4.4.0-17134-Microsoft
> Loading bnep...
> modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-17134-Microsoft/modules.dep.bin'
> modprobe: FATAL: Module bnep not found in directory /lib/modules/4.4.0-17134-Microsoft
> ./scripts/load.sh: line 21: athload: command not found
> ./scripts/load.sh: line 23: b43load: command not found
> Starting bluetooth service..
> ./scripts/load.sh: line 25: /etc/init.d/bluetooth: No such file or directory
> ./scripts/load.sh: line 26: /etc/init.d/bluetooth: No such file or directory
> make: *** [Makefile:350: load] Error 127
> scream@ADWAA:/mnt/c/users/ad/desktop/t/compat-wireless-2010-09-01$
> ```
> 
> How to fix this ؟!
> 
> This [compat-wireless-2010-09-01] was loaded because the alpha device is not working in WSL

i have same issu , please help me , its very urgent

**Comment by DHowett-MSFT** [comment]
This doesn't look like it's a console issue at all.

If this is a issue with WSL not working, then please file it on [Microsoft/WSL](https://github.com/Microsoft/WSL).
