### ISSUE TITLE
wsl ncurses programming bug, caused by incompatible terminfo

### ISSUE THREAD

**Issue by fantasiajo** [Microsoft/console#240]
I am learning ncurses on wsl. I wrote a simple program, but it isn't rendered correctly.  
```c
#include <ncurses.h>

int main(){
    initscr();
    box(stdscr,0,0);
    wborder(stdscr,'|','|','-','-','+','+','+','+');
    refresh();
    getch();
    endwin();
    return 0;
}
```
My run result is this:
![winborderbug](https://user-images.githubusercontent.com/13825949/44461117-3ca07080-a642-11e8-9f3c-d7d79f2b57e4.jpg)
Then I run it in a real debian machine and it is rendered correctly.
Then I ssh to wsl using putty  and run this code while setting putty's terminfo into **putty-256color**, the result is correct like this:
![putty](https://user-images.githubusercontent.com/13825949/44461370-247d2100-a643-11e8-8e0d-e296475b521f.JPG)

So I think it is because of incompatible terminfo of wsl.

My TERM env is: **xterm**.

Windows Version: 1803    17134

**Comment by DHowett** [comment]
This is probably MSFT:18318890; we don’t support CSI b (repeat graphic character) right now, which the xterm-256color terminfo fairly recently changed to include.

**Comment by zadjii-msft** [comment]
I concur with @DHowett, I'll put this on my backlog, hopefully I'll get to it next month-ish

**Comment by zadjii-msft** [comment]
I believe the fix for this was checked in yesterday :)

![image](https://user-images.githubusercontent.com/18356694/46221703-05894300-c303-11e8-95b2-56b2c1c87322.png)

**Comment by TheJare** [comment]
In case others run into this, I may suggest making a user-specific terminfo with the problem sequence removed, like:

`infocmp | sed 's/\(\s*\)rep=[^,]*,\s*/\1/' | tic - -o ~/.terminfo/`
