### ISSUE TITLE
Auto resize window as user change Ubuntu wsl's window size

### ISSUE THREAD

**Issue by tuyenpm9** [Microsoft/console#241]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Version 1709 (OS Build 16299.547)

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
I'm using Ubuntu wsl on windows10 and ssh to an Virutal Machine running on vmware workstation installed on windows10, I run tmux with multiple sessions.
This issue happened randomly, this is reproduce steps:
1. Open Ubuntu wsl, and pin to taskbar - trying to shortcut it and choose my favor font for this Ubuntu wsl instance - this step happens ONLY one time. (Ubuntu wsl's properties -> Font -> my favor font)
2. Ubuntu wsl in normal window size (NOT open in maximum) --> now try to maximum Ubuntu wsl, switch sessions somehow try to trigger this issue, also try to minimize Ubuntu wsl to taskbar and re-open it.
3. When you open in normal mode and do some actions in 2. you may catch the issue that appears as Ubuntu wsl has problem to redraw its size to size of maximum window and minimum one.

Issue:
![redraw_issue](https://i.imgur.com/KEJa1O0.png)

* What's wrong / what should be happening instead: This is expected window, auto resize window as user change Ubuntu wsl's window size.

Expected:
![expected_window](https://i.imgur.com/BPdA8QW.png)

**Comment by tuyenpm9** [comment]
Unfortunately or fortunately when I use directly `system32/bash.exe` I don't see this issue anymore. I'll close this issue.

**Comment by tuyenpm9** [comment]
Re-open it dues to still happens with bash.exe

**Comment by zadjii-msft** [comment]
I'm fairly certain this is by-design in tmux.

![image](https://user-images.githubusercontent.com/18356694/44670762-6e199300-a9d8-11e8-9023-cd6eab3410be.png)

If you have two different-sized terminals both connected to the same tmux session, in the bigger terminal window, it'll manually cap it's own size to the size of the smaller window, as to maintain consistency between the two.

**Comment by tuyenpm9** [comment]
Is this because of wsl resize tmux to fit when I change from maximum to minimum window? I can see tmux change the size to fit? If that is this issue from wsl or tmux can't smart enough to solve external issue?
