### ISSUE TITLE
ColorTool: Provide newer binaries

### ISSUE THREAD

**Issue by ashthespy** [Microsoft/console#259]
There have been quite a [few commits](https://github.com/Microsoft/console/compare/1708.14008...master) since the initial release binary, would it be possible to update it?

Just spent 30 mins setting up the toolchain to build it to specifically get it usable with PowerShell (https://github.com/Microsoft/console/issues/23)

**Comment by zadjii-msft** [comment]
@bitcrazed should be working on this.

It usually takes him a while to reply to GH threads, though if you want to get to him faster, [twitter](https://twitter.com/richturn_ms) usually gets him moving pretty fast :P

**Comment by bitcrazed** [comment]
On it, though I have a few high-pri things to take care of. Aiming for EOW.

**Comment by bitcrazed** [comment]
Agreed 😁

**Comment by miniksa** [comment]
Just put out 1810.02002 right now. Merged all the pending PRs, cleaned up a bug or two, and sent it out.
