### ISSUE TITLE
CTRL + SHIFT + V Pasting In WSL Not Working

### ISSUE THREAD

**Issue by Anthonykung** [Microsoft/console#264]
Hello,

I'm using Ubuntu with WSL and I could copy very well with CTRL + C or CTRL + SHIFT + C keys. But I couldn't past it with CTRL + V or CTRL + SHIFT + C no matter what. The Right-Click paste work just fine and the properties are set as well. Somehow the hotkeys just didn't work.

My build number is Microsoft Windows [Version 10.0.16299.665]

I have copied text from the browser and from within the WSL window and tried to paste it to WSL using CTRL + V and CTRL + SHIFT + V but none of them works.

I'm new to WSL, any help is appreciated.

Best wishes,
Anthony Kung

**Comment by zadjii-msft** [comment]
That functionality was only added in build 17643.

See: https://blogs.msdn.microsoft.com/commandline/2018/04/13/copy-and-paste-arrives-for-linuxwsl-consoles/
