### ISSUE TITLE
Potential regression with ScreenColors

### ISSUE THREAD

**Issue by andschwa** [Microsoft/console#267]
* Your Windows build number:  Windows Version 1803 OS Build 17134.228

* What you're doing and what's happening:

Attempting to set background and foreground colors through the registry keys, as [detailed here](https://github.com/neilpa/cmd-colors-solarized/pull/35#issuecomment-415555366).

* What's wrong / what should be happening instead: (Quoting from other issue:)

After experimenting, I think there is _currently_ a regression. `ScreenColors` is supposed to be of the form `0008 0009` where the first two bytes are the background color and the last two bytes are the text color. This is what we previously documented (in the theme), and indeed, it's how `PopupColors` is _still_ behaving.

However, it appears that the last byte of `ScreenColors` is being read for the colors, instead of two pairs of two bytes. That is, what I've set is being interpreted as `09` ending up as `base02` (color 0) and `base00` (color 9). If I edit the default value in the GUI of cmd.exe to use `base03` and `base00` (colors 8 and 9), and save this, the registry key `ScreenColors` is then saved as `0000 0089`.

So instead of the first two bytes being the background color, it appears to me that a console regression is instead reading only the last byte as the background color.

See PR to Solarized theme for console here: https://github.com/neilpa/cmd-colors-solarized/pull/35
/cc @bitcrazed

**Comment by zadjii-msft** [comment]
I don't believe it was ever read as a pair of four bytes encoding that information.

`ScreenColors` has always been a REG_DWORD that contains only one actual byte of useful information. The lowest 4 bits being the index in the color table of the foreground color, and the next-lowest 4 bits being the index of the background color. In this schema, `0x0f` is "Foreground Bright White, Background dark black"

Note that there is a pretty confusing mechanism by which the properties are actually loaded. There are probably two relevant keys in the registry: `HKCU\Console` and 
`HKCU\Console\%SystemRoot%_system32_cmd.exe`.

These work in a cascading fashion - first the console will apply the hardcoded defaults, then it will apply the settings in `HKCU\Console` (the defaults), then it'll either load properties from a shortcut (if launched via a shortcut, like Win+X, C), or it'll load any settings present in the registry for the "Title" the console was launched with (in the case of Win+R, cmd, this is translated to `%SystemRoot%_system32_cmd.exe`.

**Comment by andschwa** [comment]
> I don't believe it was ever read as a pair of four bytes encoding that information.

@zadjii-msft I am so sorry, I mispoke. I meant bits, not bytes. Post updated.

The behavior you're describing is what I expect based on previous behavior of Windows, but is not what was exhibited in the Windows Version 1803 OS Build 17134.228. My machine has since updated, so I will have to test again. But that is why it appeared to be a regression.

**Comment by andschwa** [comment]
I understand now... thank you so much @zadjii-msft
