### ISSUE TITLE
ConPTY API: TMUX on WSL over OpenSSH in Windows 10 v.1809

### ISSUE THREAD

**Issue by lars18th** [Microsoft/console#268]
Hi,

I just want to thank the team of Console regarding the ConPTY API ! It's great! :+1: 

After upgrade today to Win10 v.1809 and install the "optional" OpenSSH-Server (you need to manually set to "Automatic Start" for the Service), you can remotely use **ANY** Linux & Windows console tool with full support over SSH.

For example, after connecting to my Win10 desktop computer from my notebook using PuTTY, I do:

```
C:\> wsl

$ tmux
```

And now I can start console Linux Apps (for example the good known midnight commander `mc`) and Windows Apps (for example the too good Far Commander `far.exe`). Even in a TMUX split screen and with a full window resize !!! :open_mouth: 

Thanks a lot!

**Comment by miniksa** [comment]
You're very welcome! Getting to ConPTY was many, many years of engineering effort and we're very glad to see folks like you are happy with the result. I'll make sure the entire team sees your praise and close this issue out. Thanks for your feedback!
