### ISSUE TITLE
Cursor Disapears

### ISSUE THREAD

**Issue by mkarpoff** [Microsoft/console#269]
* Your Windows build number:  
Microsoft Windows [Version 10.0.18252.1000]

* What you're doing and what's happening: 
Type into windows cmd. Cursor disappears and does not reappear. The same problem in WSL ubuntu so it's probably a console issue. (Powershell apears unaffected though). Also worth noting if cursor blink rate in Control Panel is set to any value then the cursor will appear after a long delay.

* What's wrong / what should be happening instead: 
The cursor should not disappear in the first place

**Comment by miniksa** [comment]
I think this is MSFT:19163282. Oddly enough, I just started to look at this bug.

**Comment by mkarpoff** [comment]
Any way I can help let me know

**Comment by miniksa** [comment]
It's OK. Thanks.

I did a bisect and found where I messed this up. It was in pursuit of fixing a different cursor issue (cursor blocks being left behind in the buffer when it was scrolling). 

I'm trying to come up with a different solution to the cursor blocks left behind on scroll that keeps it from disappearing in other circumstances.

**Comment by mkarpoff** [comment]
I've just upgraded to 18262 and while it's better. The cursor takes a long time to redraw.

**Comment by zadjii-msft** [comment]
I believe we found the root of this issue and checked something in a few days ago to fix it, should be in Insiders in 3-4 weeks

**Comment by mkarpoff** [comment]
You lied to me. You said it would be fixed in 3-4 weeks. 
Can confirm 18267 Bug is gone.

**Comment by zadjii-msft** [comment]
Ah, it appears I was wrong. The fix was checked into our branch on the 5th, and it managed to get up to insiders in a record 2.5 weeks.

Glad to hear it's fixed!

**Comment by cup** [comment]
https://github.com/JuliaLang/julia/issues/33030
