### ISSUE TITLE
dark theme scrollbars

### ISSUE THREAD

**Issue by musm** [Microsoft/console#277]
can we add the option that if you are using the dark theme in windows that the scrollbars  in the prompt
![image](https://user-images.githubusercontent.com/4319522/46749913-c523b080-cc84-11e8-923e-e891358096ed.png)

match the dark scrollbars in  e.g. explorer

![image](https://user-images.githubusercontent.com/4319522/46749950-e389ac00-cc84-11e8-9886-172fd3198a45.png)

**Comment by ysc3839** [comment]
Try:
```
SetWindowTheme(GetConsoleWindow(), L"DarkMode_Explorer", nullptr);
```
In your console application.

**Comment by miniksa** [comment]
Made a change today to try this out for Insiders builds.

**Comment by musm** [comment]
@miniksa awesome, which build number? I'm on the slow ring fyi.

**Comment by zadjii-msft** [comment]
@musm It'll be out in a few weeks. It usually takes just about 3 weeks for checkins we make to get up to master, and usually a week after that for the Insider's build to get spun with the change.

So, soon<sup>tm</sup>

**Comment by oising** [comment]
Hmm, I tried what @ysc3839 said in powershell (on 1809, of course) and it had no effect on the scrollbars:

```
PS> add-type -Name NativeMethods -Namespace Temp -MemberDefinition @"
[DllImport("uxtheme.dll", SetLastError=true, ExactSpelling=true, CharSet=CharSet.Unicode)]
public static extern int SetWindowTheme(IntPtr hWnd, string pszSubAppName, string pszSubIdList);

public static extern bool IsAppThemed

[DllImport("kernel32.dll", SetLastError=true)]
public static extern IntPtr GetConsoleWindow();
"@
PS> [Temp.NativeMethods]::SetWindowTheme([Temp.NativeMethods]::GetConsoleWindow(), "DarkMode_Explorer", $null)
0
PS> # scrollbars still light theme
```
Suggestions on how to correct this, @zadjii-msft ?

**Comment by miniksa** [comment]
I'm really not sure why it doesn't work from the outside. Could be that it doesn't like being done after `ShowWindow` has been called and the `WM_SETTINGCHANGED` handler isn't ready for it. Could be that `SetWindowTheme` generates a window message that UIPI is blocking from your Powershell binary. Could be something completely different. I'm sorry. I tried it inside the console code and it works, so I'm not intending to spend anytime debugging why it doesn't work from the outside.

**Comment by musm** [comment]
(unrelated) @ysc3839 can you provide me with some simple minimal example with that ? Trying to dive in so I can create PRs for some apps I use, but win32 API and world is a little dizzying for first timers.

**Comment by ysc3839** [comment]
@musm 
It works on my GUI application. Currently I have not tested on console Windows.
Maybe SetWindowTheme for external process is not allowed.

https://github.com/ysc3839/VCMPBrowser/blob/darkmode/DarkMode.h
This code uses internal APIs and may not work on a newer Windows version.

**Comment by be5invis** [comment]
Does the dark mode cover settings dialog?

**Comment by miniksa** [comment]
MSFT: 19271078 reached Insiders for 18272+.

The follow on fix for a mistake (MSFT: 19548142) reached Insiders for 18309+.

**Comment by ysc3839** [comment]
@miniksa I reverse engineered and found you use GetProcAddress with a magic number. Why not static link to that function?
I'm afraid that the console will broken when the ordinal of that function changed.

![image](https://user-images.githubusercontent.com/12028138/52904788-c5077300-326b-11e9-9fd9-aa9211683a83.png)

**Comment by Biswa96** [comment]
@ysc3839 Do not post reverse engineering-ed screenshot. Your concept is wrong. Email me.

**Comment by Biswa96** [comment]
@ysc3839 Do not post reverse engineering-ed screenshot. Your argument is wrong. Email me. It is internal matter.

**Comment by Biswa96** [comment]
@ysc3839 Do not post reverse engineering-ed screenshot. Your argument is wrong.

**Comment by DHowett-MSFT** [comment]
@ysc3839 There's a couple reasons for that:

1. The function may not be exported by name.
2. We can't statically link it, as the library that provides it is a dynamic library.
3. We all use the console internally every day, and are very likely to be the first to know if this ordinal changes, probably through a change in its observable behavior. Since we're developing on builds of windows that are _very close_ to mainline, we'll almost certainly figure out changes like this before any breakage makes it out to Insiders.
   1. (additionally, any given ordinal is not at risk of changing during the lifetime of a single version of Windows)

**Comment by ysc3839** [comment]
@DHowett-MSFT 
Sorry, the "static link" means link to that DLL using import address table.
Some other DLL (explorerframe.dll) link to that function using IAT. It's better than using GetProcAddress.
