### ISSUE TITLE
Regression in cursor blink/display behavior on navigation

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/console#284]
There is a regression that's popped up somewhere in the fast track builds between 18214 and 18252 regarding the behavior of the displayed caret/cursor.

[Behavior was observed under fish](https://github.com/fish-shell/fish-shell/issues/5254), the long and short of it is that the cursor disappears when navigating within the commandline buffer left and right, and you don't know where it's positioned (zero visual feedback) until the blink timeout elapses 0.5/1s later and the cursor reappears, extremely hindering productivity.

Previous versions of Windows (18214/17763) would keep the cursor visible while keying left/right, regardless if it was in block or underline mode. Under 18252, the cursor immediately vanishes completely on left/right navigation, and does not reappear until navigation has ceased and the timeout elapses.

**Comment by Erebuxy** [comment]
I believe this is the same as Microsoft/console#269.

**Comment by mqudsi** [comment]
I believe you're right. Thanks @Erebuxy .
