### ISSUE TITLE
emacs changes cursor's look

### ISSUE THREAD

**Issue by tsdeng** [Microsoft/console#286]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17763.55]

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
1. Install ubuntu 18.04 from Microsoft App Store
2. Start the bash of ubuntu 18.04
3. Install emacs 25 with "sudo apt install emacs 25"
3. Right click the title bar of the console window.
4. Select Properties.
5. Set Options->Cursor Size to "Large"
6. Start emacs by "emacs"
7. After emacs is launched, right click the title bar, select Properties->Options->Cursor Size, you will see the Cursor Size is being reset to "Small"

* What's wrong / what should be happening instead:
What's wrong is in step 7, where the cursor size should not be reset to "Small". What should be happening instead is it should keep the existing configuration, which is "Large" in this case.

**Comment by zadjii-msft** [comment]
Looks like cursor size is another property that doesn't propagate to the alt buffer. Definitely related to #177

**Comment by miniksa** [comment]
It looks like this was tracked by MSFT: 19302443. That issue reached Insiders for 18309+ and should be in any build built after 2018-12-20.
