### ISSUE TITLE
Rclone console output does not properly get cleared before updating it

### ISSUE THREAD

**Issue by SL-Gundam** [Microsoft/console#289]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17763.55]

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
Just wanted to let you know that with the Windows 10 1809 update the console does not clear old output properly in Rclone. In Windows 10 1803 this was not an issue but with 1809 it is.

Proper output with Windows 1803
![image](https://user-images.githubusercontent.com/912973/46822374-9d6b4000-cd8b-11e8-8947-4e6a8b071ab9.png)

Output not properly cleared with Windows 1809
![image](https://user-images.githubusercontent.com/912973/46491824-1c043280-c80c-11e8-911f-ad71baec88a2.png)

* What's wrong / what should be happening instead:
The output of the console should be properly cleared or updated. For the moment i've only encountered this in Rclone
The issue is also reproducible when using Powershell instead of cmd to run rclone

I reported this to the Rclone dev team here: https://github.com/ncw/rclone/issues/2623
But its unclear what change caused this and what must be done to fix this (either in rclone or in windows)

For the moment i've found a workaround
I enabled "Use legacy console" and that resolved it for me
![image](https://user-images.githubusercontent.com/912973/46573277-4cc2a400-c993-11e8-9cc3-8e6e75d1ae8d.png)

**Comment by zadjii-msft** [comment]
Filed MSFT:19313218 internally to investigate. Thanks for finding this!

**Comment by miniksa** [comment]
I have just submitted a fix for this issue today. It should reach Insiders builds in 2-3 weeks.

**Comment by DHowett-MSFT** [comment]
A fix for this shipped in 19H1 Insider Build 18312.

**Comment by mb300sd** [comment]
Any chance a hotfix gets released for 1803/Server 2019? We need Desktop Experience so the SAC is not an option.

**Comment by SL-Gundam** [comment]
In that case i would activate legacy mode as seen in earlier screenshots
