### ISSUE TITLE
Dark mode needs dark titlebar, like Explorer, Settings, Edge, etc.

### ISSUE THREAD

**Issue by Jaykul** [Microsoft/console#299]
The new (18272) dark-mode scroll bar is nice, but the title bar is still white when the app is focused.
It correctly goes to the "accent color" when it's not active (if you have that on in settings), but goes to white when it looses focus. 

Need I say more?

![image](https://user-images.githubusercontent.com/192942/47948022-ba181500-defe-11e8-9315-beb925c26051.png)

Microsoft Windows [Version 10.0.18272.1000]

**Comment by DHowett-MSFT** [comment]
@miniksa, unaware that somebody had reported it, just submitted (and merged!) a pull request that fixes this.
Thanks!

**Comment by DHowett-MSFT** [comment]
A fix for this shipped in 19H1 Insider Build 18312.

**Comment by MathiasMagnus** [comment]
How can the fix be applied? I am on Windows 1903, I just built the app from the latest tagged version and no matter what the `profiles.json` says under `requestedTheme`, may it be `"system"` or `"dark"`, the title bar is always snow white.

**Comment by ysc3839** [comment]
@MathiasMagnus This issue is about Console Host. Not Windows Terminal.
Related code: https://github.com/microsoft/terminal/blob/6c7dfd2ce45841d32f3990147506de2f7903485d/src/interactivity/win32/windowtheme.cpp#L1-L119

**Comment by Biswa96** [comment]
@ysc3839 Is there any code fix for this?

**Comment by ysc3839** [comment]
@Biswa96 No such issue on 10.0.18362.356.
