### ISSUE TITLE
Get rid of CP/M reserved file names

### ISSUE THREAD

**Issue by be5invis** [Microsoft/console#301]
I mean, `CON`, `PRN`, `AUX`, `NUL`, `COM1`, `COM2`, `COM3`, `COM4`, `COM5`, `COM6`, `COM7`, `COM8`, `COM9`, `LPT1`, `LPT2`, `LPT3`, `LPT4`, `LPT5`, `LPT6`, `LPT7`, `LPT8`, and `LPT9`, At least when used with a extension (like `AUX.txt` rather than single `AUX`).

**Comment by HBelusca** [comment]
You surely break scripts (batch files) that rely on these.
One idea would be to have a CMD.exe switch that can disable these special names.
Also, some of these names are specially handled in the RTL of ntdll.dll.

**Comment by be5invis** [comment]
@HBelusca 
I do not think someone would write `whatever > NUL.txt` instead of `whatever > NUL`.
Do we have telemetry?

**Comment by doubleyewdee** [comment]
Isn't the problem with these filenames buried much deeper in Win32-land? I didn't think this was under the control of cmd.exe (or PowerShell.exe) themselves. Amusingly I successfully made a file called 'NUL' from WSL in my $TEMP dir in Windows but nothing in cmd/powershell wants to interact much with it. 🙃

**Comment by HBelusca** [comment]
The Windows team would just have to modify `RtlIsDosDeviceName_U()` and `RtlIsDosDeviceName_Ustr()` (in ntdll) to return 0 everytime in order to disable checks for "DOS device names" (as these COM/LPT/... are called).

**Comment by zadjii-msft** [comment]
I concur with @doubleyewdee. There's nothing that my team is going to be able to do that, and changing this behavior would be a massive compat nightmare. 

Sure, the code change itself _might_ be easy, but the potential fallout would be incalculable. I'm gonna go ahead and just say no on this one.
