### ISSUE TITLE
Background color reverted when clicking 'Properties'

### ISSUE THREAD

**Issue by deto** [Microsoft/console#31]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

* What's wrong / what should be happening instead:

(Note, I'm doing all of this by typing 'cmd' into my Explorer address bar...which I believe is just a proxy for running C:\Windows\System32\cmd.exe)

If I run `colortool.exe solarized_light` everything looks fine.  

![image](https://user-images.githubusercontent.com/551879/30405605-b5533a8a-98a1-11e7-9d4d-c7001a698438.png)

However, if I then go into the properties, it looks like this (note 'Screen Background')

![image](https://user-images.githubusercontent.com/551879/30405629-cfe3d1b6-98a1-11e7-9cb3-75e9de24dbe3.png)

and as soon as I click 'OK' (without clicking anything else in the Properties window) the background changes back to black (not sure about other colors?)

![image](https://user-images.githubusercontent.com/551879/30405647-ea128910-98a1-11e7-85af-0f1f3b08530c.png)

Any idea what's going on?  I'd expect the Properties window to reflect the current palette and then just save those colors when I hit Ok.

Running Windows 10, Versoin 1703, Build 16251.1002

**Comment by zadjii-msft** [comment]
Oh yea this is related to #15 (or at least part of it). For some reason, the colors property sheet would sometimes forget to initialize the value of the first entry (leaving it defaulted to 0,0,0). I believe that @paulcam put a fix for this into main a while ago, so I think it might be in the Fall Creator's Update (whenever that lands), but if not then it should be fixed in Insider's builds soon after that.
