### ISSUE TITLE
Unable to set colors above index 15 with OSC 4

### ISSUE THREAD

**Issue by zadjii-msft** [Microsoft/console#313]
From #81:

Conhost doesn't support setting color table entries above 130.

Here's xterm printing in 130 by default:
![image](https://user-images.githubusercontent.com/18356694/49031503-f6860c00-f15e-11e8-9d72-1bd519dc1c3a.png)

I couldn't get the syntax just right, but for example, you definitely can change the colors of the extended table:
![image](https://user-images.githubusercontent.com/18356694/49031740-af4c4b00-f15f-11e8-90b9-ddbac7d62b4f.png)
Note how color 130 is now a black square, instead of the color it usually is

**Comment by zadjii-msft** [comment]
MSFT:19723934

**Comment by miniksa** [comment]
I checked this morning and this fix should be in Insiders builds 18312 and higher (build on or after 2019-01-04).

**Comment by DHowett-MSFT** [comment]
This one's a little funny, actually. Most of the fix is in 18312, but it'll only work for colors 0-99. Colors 100-255 will probably be in whatever insider build comes next.

**Comment by miniksa** [comment]
Yes, sorry, this one had two changelists on it. It's also inbound.

**Comment by DHowett-MSFT** [comment]
This is now fully supported as of insider's build 18334.
