### ISSUE TITLE
19H1+: Invert (^[[7m) doesn't work properly

### ISSUE THREAD

**Issue by DHowett-MSFT** [Microsoft/console#315]
### Expected

![image](https://user-images.githubusercontent.com/14316954/49317913-3f192e80-f4ab-11e8-897a-c67219923cef.png)

(The bug on the first line is caused by #78; please ignore. Pretend it is white on green.)

### Actual

![image](https://user-images.githubusercontent.com/14316954/49317922-47716980-f4ab-11e8-9387-8640a8a7be61.png)

Tracking MSFT:19694089

**Comment by zadjii-msft** [comment]
Understood, in PR. Before, after:

![image](https://user-images.githubusercontent.com/18356694/49318811-d9c73c80-f4ae-11e8-883a-78d15ce616a0.png)

Turns out I fixed this while working on #78

**Comment by DHowett-MSFT** [comment]
A fix for this shipped in 19H1 Insider Build 18312.
