### ISSUE TITLE
build 18298.1000 console breaks with WSL

### ISSUE THREAD

**Issue by nicferrier** [Microsoft/console#325]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.18298.1000]

* What you're doing and what's happening: (Copy&paste specific commands and their output, or include screen shots)

For example:

- start WSL,
- vi ~/.bashrc
- quit vi

console no longer prints anything.

It can be reset by doing ls -la.

If you have emacs installed:

- emacs -nw
- screen looks wierd
- quit emacs
 
console now has a red background.

The same sort of thing happens with htop, less and I guess any terminal app using colors?

* What's wrong / what should be happening instead:

curses apps should be working.

**Comment by bitcrazed** [comment]
I LITERALLY just came here to file this bug and found that @nicferrier got there first! :) NICE! 🍾 

Another repro:

From Cmd/PowerShell, if I run:
```
C:\>wsl man ls
```
 
The man page appears and everything is fine. Then when I hit <key>q</key> to exit, it drops back to the Cmd/PowerShell, but the foreground color is the same as the background color:
```
C:\>wsl man ls
 
                  _
```

Only if I execute `color` to reset the colors can I see the text again. This didn’t used to happen. It happens with any kind of interactive command in WSL.

**Comment by oising** [comment]
Yeah, just noticed this too on 18298, which took about eight attempts to install on top of 18290. Sheesh - is this the reward I get for my persistence? 🤣

**Comment by nicferrier** [comment]
> 
> 
> Yeah, just noticed this too on 18298, which took about eight attempts to install on top of 18290. Sheesh - is this the reward I get for my persistence? 🤣

Frustrating isn't it? But Microsoft are slowly fixing the console stuff which has been broken for ever (35 years?) so I try to sniff a candle or have a bath or something to reduce my frustration.

**Comment by DHowett-MSFT** [comment]
This should work as of 18309 or 18312.
