### ISSUE TITLE
[Feature Request] Cycle only unique commands

### ISSUE THREAD

**Issue by Splike** [Microsoft/console#328]
After reading this blog post on [New Experimental Console Features](https://blogs.msdn.microsoft.com/commandline/2018/12/10/new-experimental-console-features/), I thought this was the right time to ask for a feature request, that could be added to the terminal options. (Or maybe even made as default behaviour?)

When cycling previously run commands with the up-arrow, it will take 8 key-presses to reach the `ls` command in the example below
(read from bottom to top)

```
$ ls
$ java main.
$ javac main.java
$ java main
$ javac main.java
$ java main
$ javac main.java
$ java main
```
But I want an option to remove duplicate commands, when cycling through them, so in the example, it would only take 3 key-presses
(read from bottom to top)

```
$ ls
$ javac main.java
$ java main
```

**Comment by zadjii-msft** [comment]
Ah, that'd be a `cmd.exe` feature request, not a `conhost` feature request. `cmd` is the shell application, while `conhost` is the console or terminal application, responsible for drawing commandline apps.

What the "Experimental" new features applies to is the console, not the shell. We unfortunately can't add any new features to cmd.exe, full stop. It doesn't matter how good of a feature idea it is, we unfortunately just can't do it :/

The official party line is if you'd like new shell features, I'd recommend powershell, as they're opensource and accepting community contributions with regards to shell features.

**Comment by oising** [comment]
Really? 

![image](https://user-images.githubusercontent.com/1844001/50030702-8848a280-ffc2-11e8-860a-cb019afa8def.png)

**Comment by Splike** [comment]
> Really? This feature has been there for as long as I can remember...

Thanks for letting me know about this. But ticking the box of a WSL window does nothing, compared to a powershell window, where it works.

**Comment by Splike** [comment]
@zadjii-msft 

The option showed by oising above, does what I want. The problem is that it works for Powershell and cmd. But in my WSL Ubuntu window, the option has no effect. Even after restarting the application.

**Comment by zadjii-msft** [comment]
I literally forgot that that checkbox existed until just now.

I guess that affects the history parts of the console API, which both cmd and powershell use. WSL shells however don't use the console API's at all. This sounds like a feature request for `bash` or whatever linux shell you're using, nothing we can really do to control those applications.

**Comment by oising** [comment]
History management in Ubuntu is part of your chosen shell. Maybe this can help: https://stackoverflow.com/questions/338285/prevent-duplicates-from-being-saved-in-bash-history
