### ISSUE TITLE
Handle leak with ConPty implementation - pipelistener thread won't exit.

### ISSUE THREAD

**Issue by EricYoungdale** [Microsoft/console#329]
I was starting to try some more extensive examples.  All such examples seem to have a relay thread that reads from the pipe and writes to the console.  The issue I see is that when the child that we are launching actually exits, that the pipe isn't broken and the relay thread just sits there.  What seems to happen is that conhost.exe also has a copy of the pipe - if I manually kill that in the task manager, then the relay thread finally breaks.  Or I can use process explorer to "close" the offending handle - same thing.  Once I do this, then the pipe read in the listener thread will exit with ERROR_BROKEN_PIPE.

It does not seem to matter if I make the pipe handles uninheritable before creating the pseudo terminal - so far nothing that I have tried will cause conhost to not hold open a pipe handle.

**Comment by DHowett-MSFT** [comment]
> when the child that we are launching actually exits ...

I think this is intentional. Like a pty, a pseudoconsole exists regardless of it having any attached children. Since it's held open, you should be able to reattach any number of children to it.

If you use `ClosePseudoConsole`, it should terminate the conhost and relinquish the pipe handle.

**Comment by zhiburt** [comment]
I take it to be related.

Is there any way then how to not block on reading in cases where we reading in loop and process gets terminated??

https://stackoverflow.com/questions/68985384/does-a-conpty-reading-pipe-get-notified-on-process-termination
