### ISSUE TITLE
[WSL] Console output disappears after editting a file in Vim

### ISSUE THREAD

**Issue by nernst** [Microsoft/console#338]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Version 10.0.18305.1003

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
When using Bash on Windows (WSL) with Ubuntu 18.04, sporadically when exiting Vim on a remote host via ssh, the console stops rendering new text. It doesn't happen all of the time, and it seems that re-entering vim, then exiting immediately solves the problem; no need to close & restart the shell.

What I've seen is that the cursor appears to be in the correct place, and it blinks as usual. The cursor moves in response to key presses. Key presses are sent, as when I'm in this state, I can type 'vim' and vim properly starts and renders. While I'm in vim, everything works as expected. When I exit vim (for the second time), it usually resets and the console works properly again.

* What's wrong / what should be happening instead:
I would expect that after quitting Vim, that the console would behave as normal. i.e. key presses are properly echo'd, the prompt is rendered, etc.

**Comment by DHowett-MSFT** [comment]
This looks like it might be #325.

**Comment by nernst** [comment]
Agreed. I did look through open issues, but didn't see anything that matched. This is likely a duplicate.
