### ISSUE TITLE
windows touch keyboard works incorrectly in WSL

### ISSUE THREAD

**Issue by ns740** [Microsoft/console#342]
* My Windows build number:  
`Microsoft Windows [Version 10.0.17134.472]`

* What i'm doing and what's happening:  

Originally I reported this as a WSL issue but i'm moving here in response to 
this reply from @therealkenc here:  
[https://github.com/Microsoft/WSL/issues/2483#issuecomment-451708681](https://github.com/Microsoft/WSL/issues/2483#issuecomment-451708681)  

I am using a Surface Pro 4 in tablet mode, running Ubuntu [Ubuntu 16.04.5 LTS] in WSL.

Various things that work correctly with an attached hardware keyboard fail to work correctly with the touch keyboard.   For example:
1. entering a password (containing an uppercase character) when prompted after a "sudo ls" command in bash (and clicking "ENTER" after typing the unechoed password).  
In this case the password is rejected even when i am "extra sure" i am typing the correct password.
2. editing a file in vim and then attempting to exit by typing these keystrokes:  
`[ESC] : q [SHIFT] 1`        
(`[SHIFT] 1` is the way to type the "!" character on the touch keyboard)  
in this case (unlike 1 above) there is visible evidence of strange behavior because the expected echoed command at the bottom of the vim screen is    
`:q!`  
BUT it actually is    
`:q^@!`  
my version of vim doesn't mind the extra "`^@`" and executes the exit command anyway but this is a way to get visual confirmation of the unexpected keyboard behavior	 
3. from a bash prompt enter:  
`tmux`  
`[CTRL] b [SHIFT] "` &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
_(to open a new tmux pane below the the current pane)_  
using the touch keyboard displays "`"`" instead of opening a new pane as expected

**Notes**
  1. if instead of using the windows 10 touch keyboard, I use the `osk.exe` "Onscreen Keyboard" the problem does not occur.   (In example 1 above, hitting `[ENTER`] after typing the correct password works as expected.   In example 2, "`:q!`" appears in the vim command line as expected and in example 3 the pane opens as expected)   
  2. if instead of using the windows 10 touch keyboard to type the password in example 1, the password is copied to the windows clipboard and pasted into the console window (using a longpress - the touch equivalent of a right-click) the password is accepted as expected

**Comment by DHowett-MSFT** [comment]
This looks like it might be a more detailed report of #215. Thanks!
