### ISSUE TITLE
ps u core dumps

### ISSUE THREAD

**Issue by jimmydjurle** [Microsoft/console#343]
after doing apt upgrade 2019-01-07 the ps command starts to core dumps.

uname -a
Linux LAPTOP-K955K4SE 4.4.0-17134-Microsoft #471-Microsoft Fri Dec 07 20:04:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

ps u
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
Signal 11 (SEGV) caught by ps (procps-ng version 3.3.10).
kappen   24124  0.0  0.0  15264  3888 tty1     Sps:display.c:66: please report this bug
Segmentation fault (core dumped)

**Comment by zadjii-msft** [comment]
I'm not sure how this is related to the console - if this is a WSL bug, could you file instead on the [https://github.com/Microsoft/WSL](WSL) repo?
