### ISSUE TITLE
Powershell doesn't colorize commands cmdlets

### ISSUE THREAD

**Issue by pldg** [Microsoft/console#348]
**Windows build number:**  Microsoft Windows [Version 10.0.17763.253]

Commands I type in powershell should appear colored

See the screenshot below

![image](https://user-images.githubusercontent.com/24630716/51108863-bd2f5b80-17f3-11e9-8df4-5657f33ede3c.png)

- `get-vm` should be colored in yellow
- `wsl` should be colored in yellow
- `"ubuntu"` should be colored in dark-cyan

**Comment by pldg** [comment]
Yes, version 2.0

![image](https://user-images.githubusercontent.com/24630716/51133497-6d718400-1835-11e9-8592-cc695eb2d0da.png)

**Comment by miniksa** [comment]
I'm honestly not sure from here. PSReadline is what does the coloring and isn't a component owned by the console system team. Perhaps it is misconfigured?

I'm trying to reproduce internally on a fresh machine and I see the coloring.

@SteveL-MSFT, do you have any ideas here?

**Comment by DHowett-MSFT** [comment]
You might try `Get-PSReadlineOption`. For me, it prints the following (with colors and all):

![image](https://user-images.githubusercontent.com/14316954/51134564-d254bc00-17ec-11e9-94cc-917f253e7fbf.png)

There's a chance your options are missing or misconfigured, especially if you'd configured them in your PowerShell profile for PSReadline 1.0.

**Comment by pldg** [comment]
Run `Get-PSReadlineOption` throw an error

![image](https://user-images.githubusercontent.com/24630716/51135101-8a0fbb00-1839-11e9-92e4-9af7c3bad0ef.png)

Probably is misconfigured, but I can't remember to have ever tweaks those settings

**Comment by DHowett-MSFT** [comment]
It looks like there's something wrong with the PSReadline module installed on your system. That'll have to be filed over at lzybkr/PSReadline or PowerShell/PowerShell.

**Comment by pldg** [comment]
The problem occur only after a Windows update (not sure what build exactly) which seems to also upgrade PSReadLine to version 2.0 which itself is the cause of this bug but only if you are running powershell with a keyboard layout different from en-US

**Two possible way to fix this bug:**

- Method 1: close powershell, change keyboard layout to en-US, re-open powershell
- Method 2: downgrade PSReadLine to 1.2

Source: https://github.com/lzybkr/PSReadLine/issues/614#issuecomment-424910427
