### ISSUE TITLE
One cell at the right end of the screen is ignored

### ISSUE THREAD

**Issue by ntak** [Microsoft/console#357]
One cell at the right end of the screen is ignored by ConPTY (18317). (17763) does not.
I tried it with ConPTY sandwiched by Vim, but it does not look like this in winpty.
It uses VMware12.
It seems that backspace is shifted to the left by one cell when you hit repeatedly across lines.

![windows-10-insider---vmware-workstation-2019-01-20-13-49-46](https://user-images.githubusercontent.com/44701315/51435582-0f71f000-1cbe-11e9-9ea7-3122e97e8f86.gif)

**Comment by zadjii-msft** [comment]
Okay, so to make this clear, his is something that's regressed since RS5 (17763). 
Looks like even in wsl interop this repros. I've filed MSFT:20266233 to make sure this gets fixed.

![image](https://user-images.githubusercontent.com/18356694/51554054-2c770200-1e29-11e9-8dea-43475e19d4fc.png)

**Comment by DHowett-MSFT** [comment]
Hey, I forgot to tag this one! It's fixed as of insider build 18834.
