### ISSUE TITLE
conhost crashes when Vim is run via ConEmu

### ISSUE THREAD

**Issue by bgshacklett** [Microsoft/console#36]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
```
Microsoft Windows [Version 10.0.17025.1000]
```

* Vim Version
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 22 2017 22:02:21)
MS-Windows 64-bit console version
Included patches: 1-1213
Compiled by appveyor@APPVYR-WIN
```

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
1. Open a new ConEmu instance.
2. Type `vim`, then press the Enter key

* What's wrong / what should be happening instead:
  * conhost.exe crashes
  ```
  Faulting application name: conhost.exe, version: 10.0.17025.1000, time stamp: 0x9d420209
  Faulting module name: ntdll.dll, version: 10.0.17025.1000, time stamp: 0x174af1e9
  Exception code: 0xc0000374
  Fault offset: 0x00000000000f511b
  Faulting process id: 0x28a8
  Faulting application start time: 0x01d351c58f135167
  Faulting application path: C:\WINDOWS\system32\conhost.exe
  Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
  Report Id: ac139509-a65e-4a2d-80a2-2e7a3c48df2b
  Faulting package full name: 
  Faulting package-relative application ID: 
  ```
  * Vim continues running until it's terminated.
  * Vim's CPU utilization jumps significantly, pegging the CPU at 100%
  * After Vim is terminated, I get an error stating that PowerShell has stopped working.

* Other Notes:
Similar behavior arises when attempting to run NeoVim (`nvim.exe`) with $env:TERM=xterm-256color

**Comment by zadjii-msft** [comment]
Well that looks bad. We haven't pushed out too much code in that insiders build, but that could be our fault.

Filed a bug to investigate more.

**Comment by bgshacklett** [comment]
If there's anything else I can do to help (capturing logs, etc.); I'd be happy to do so.

**Comment by bgshacklett** [comment]
One thing I forgot to mention, I believe it started in the previous build (17017?).

**Comment by adiviness** [comment]
Where did you get that version of vim and what version of conemu are you using? this doesn't repro for me with the latest stable versions of those two. my vim says `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 23 2017 19:48:19)` (x86 version) and conemu is the x64 version 161206 stable.

**Comment by adiviness** [comment]
Also, does this only happen when vim is run through conemu or does it crash when run through the normal console as well?

**Comment by bgshacklett** [comment]
It's only when running through ConEmu (with a custom or default config). I downloaded Vim straight from the repo's releases section (https://github.com/vim/vim-win32-installer/releases), and I got the latest version of ConEmu via the built-in automatic update feature. I'll have to verify the version of ConEmu, but I believe it's version 171025, as I updated just prior to opening the issue and that would have been the latest available version at the time. I'll try downgrading it again and verifying that the problem still exists. I'll see what I can do to repro in a fairly vanilla environment, as well.

**Comment by bgshacklett** [comment]
I've tried two versions of ConEmu: 170807 and 171025. Both of these were downloaded via the built-in update mechanism. Just for the heck of it I went and installed the "stable" version, 161206 and I was able to reproduce the problem with that version as well. No word, yet, on a repro in a a clean environment.

**Comment by khouzam** [comment]
If you can attach a debugger to conhost.exe and capture a full dump of the crash we can at least get some insight on the root cause.

**Comment by bgshacklett** [comment]
Can do. I'll report back with the details as soon as I get a moment.

**Comment by bgshacklett** [comment]
I got a memory dump today. It's available at https://1drv.ms/u/s!Arz_LjDR8MD-qxhrmA0DCkRrfchr. Please let me know if I can do anything further to help.

**Comment by khouzam** [comment]
Thanks a lot @bgshacklett,

This is a known bug that we've had. It's been addressed and the fix will be available in a future flight.

**Comment by bgshacklett** [comment]
@khouzam I don't suppose you might be able to provide a bit of info as to how this bug is encountered, would you? I'd like to open an issue on https://github.com/Maximus5/ConEmu, but it would be very helpful to have some information as to how to implement a workaround prior to doing so. It must be possible, as I've been using Vim with ConEmu on Windows for years; I just started having trouble recently.

Thanks!

**Comment by khouzam** [comment]
Please don't open an issue around this. This is only affecting insider builds and is a bug in the console code. It is already addressed and will make its way to insiders soon (don't know the exact flight). The usual way that the crash happens is when the buffer resizes itself, there's not much that an application could do to work around it.

**Comment by bgshacklett** [comment]
Ahh, my apologies; when you said it was a known bug I assumed that the scope was broader than just the insider builds. I'll just leave it alone and be patient, then. Thanks for the clarification!
