### ISSUE TITLE
ColorTool not apply for PowerShell (Adminstrator)

### ISSUE THREAD

**Issue by H9j8** [Microsoft/console#360]
I try change colors schema for PowerShell but it only apply when run as normal and it doesn't apply when **run as administrator**

![screenshot_1](https://user-images.githubusercontent.com/12744590/51778672-9ba86b00-2135-11e9-8f8e-dfacf7114d5d.png)

**Comment by kid1412621** [comment]
@H9j8 Could you tell me what action you take in Properties and Defaults? I've tried it out, but still not working. I cannot believe this buggy software comes from MS.

**Comment by changbowen** [comment]
@kid1412621 i think he meant after you apply the color scheme with colortool.exe -b <scheme>, you need to right-click on the title bar, open "Defaults" from the menu and then just click OK to close the "Defaults" window. That will tell the console to save the colors. Same rule applies on Properties as well.
