### ISSUE TITLE
Windows子系统Ubuntu控制台在哪里

### ISSUE THREAD

**Issue by DENGQIANCHENG** [Microsoft/console#379]
This bug-tracker is monitored by Windows Console development team and other technical types.  **We like detail!**

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  

> **Important: When reporting BSODs or security issues, DO NOT attach memory dumps, logs, or traces to Github issues**. Instead, send dumps/traces to secure@microsoft.com, referencing this GitHub issue.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

* What's wrong / what should be happening instead:

**Comment by miniksa** [comment]
This issue contains no data. Closing.
