### ISSUE TITLE
Include Braille characters in Consolas

### ISSUE THREAD

**Issue by be5invis** [Microsoft/console#385]
I do not think even we supported font fallback, the glyphs in fallback fonts can be well-aligned with Consolas' metrics. So could we simply include that?

**Comment by zadjii-msft** [comment]
Hey I'm gonna dupe this to #387 - if we add any characters to Consolas, then we'll probably do all of them, no need to separate out the threads (in this case).

**Comment by walraymmo** [comment]
Take... 
I needed it too, so I included the characters.
[Consolas-Braille.zip](https://github.com/Microsoft/console/files/3031590/Consolas-Braille.zip)
