### ISSUE TITLE
ConPty in CMake/Qt project - pipes don't work

### ISSUE THREAD

**Issue by kafeg** [Microsoft/console#388]
Hello!

I try to create Qt binding for ConPty and I use CMake as build-system for my project. And my problem is: ConPty doesn't write its own output to a pipe, it just write all into stdout of my main process. As if a child and my parent stdout channels merged. I try to create a realization with named and anonymous pipes (from EchoCon example), but it both fail =(

I don't know what I do wrong - all my code are the same of EchoCon example, but project not work as expected.

Information about my system:
- Microsoft Windows [Version 10.0.18342.8]
- Windows SDK Version 10.0.18346.0

I build my project with cmake in Qt Creator with MSVC. I double checked, cmake use latest available SDK. Also original EchoCon sample is working fine on my system, but copied from it code built with cmake - not =(

You can find not working code here: https://github.com/kafeg/ptyqt/blob/master/core/conptyanonymouspipeprocess.cpp

**Comment by DHowett-MSFT** [comment]
Hey @kafeg,
It looks like you're [reading from the input pipe](https://github.com/kafeg/ptyqt/blob/master/core/conptyanonymouspipeprocess.cpp#L190) and [writing to the output pipe](https://github.com/kafeg/ptyqt/blob/master/core/conptyanonymouspipeprocess.cpp#L301). Try switching those around and seeing what ends up in your read buffer.

**Comment by kafeg** [comment]
@DHowett-MSFT, sorry, but are you sure?

In original example are the same pipe used to read from Pty:
```cpp
//  Create the Pseudo Console and pipes to it
HANDLE hPipeIn{ INVALID_HANDLE_VALUE };
HANDLE hPipeOut{ INVALID_HANDLE_VALUE };
hr = CreatePseudoConsoleAndPipes(&hPC, &hPipeIn, &hPipeOut);
...

// Here used 'hPipeIn' as parameter for PipeListener
HANDLE hPipeListenerThread{ reinterpret_cast<HANDLE>(_beginthread(PipeListener, 0, hPipeIn)) };
...

//and PipeListener:
void __cdecl PipeListener(LPVOID pipe)
{
    HANDLE hPipe{ pipe };
    ...
    fRead = ReadFile(hPipe, szBuffer, BUFF_SIZE, &dwBytesRead, NULL);
    ...
}
```
And this combination works.

**Comment by kafeg** [comment]
So, I try switch pipes, but it still not work =(

**Comment by kafeg** [comment]
All works fine, an important part is to run the application from the existing console window.
