### ISSUE TITLE
Color bleed if scrolled on 1903

### ISSUE THREAD

**Issue by isral** [Microsoft/console#419]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.18362.30]
* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
SET PROMPT=$e[37;1;42m$T$S$P$_$G$e[37;0;40m
Do command that will scroll window like dir on C:\Windows
Color bleed
* What's wrong / what should be happening instead:
**The color doesn't bleed on 1803**
The 1st and 2nd prompts are OK but not the 3rd.

![image](https://user-images.githubusercontent.com/3161234/56843841-b6bf7e00-68d0-11e9-9353-a147533fd064.png)

https://github.com/Microsoft/console/issues/129

**Comment by zadjii-msft** [comment]
This is by-design from the resolution of the issue you linked. The fact that the color didn't bleed in 1803 was a bug, not by design. Conhost behaves more correctly now.

You should update your prompt to have a `$e[m` before the newline.

**Comment by Biswa96** [comment]
@zadjii-msft I've this `$E[30;47m$P$E[0m$_$$$G` in prompt. Also shows same issue when I maximize and minimize the cmd window.

**Comment by zadjii-msft** [comment]
@Biswa96 I'm not seeing that with the same prompt locally.

I do see _this_ however. Before:
![image](https://user-images.githubusercontent.com/18356694/56902921-e1d8d780-6a60-11e9-91cb-118f6a25a5b4.png)

after a maximize:
![image](https://user-images.githubusercontent.com/18356694/56902934-eb623f80-6a60-11e9-9acc-3e72cc5a7fa2.png)


See that the color form the prompt line has filled the entire line on a resize.

This has been a particularly long-standing bug that's quite hard to solve, and unrelated to the issue in this thread and the linked thread.
