### ISSUE TITLE
Console Cursor for Dark Grey Background Disappears

### ISSUE THREAD

**Issue by consentfactory** [Microsoft/console#54]
* Your Windows build number:  
10.0.16299.98

* What you're doing and what's happening:
Changing background color of console to 'dark grey' and terminal cursor disappears.
Demo here:
https://twitter.com/consentfactory/status/956520606756896768

* What's wrong / what should be happening instead:
Cursor should be appear in a contrasting color, blinking

**Comment by zadjii-msft** [comment]
Well, it looks like that's a color that's it's own inverse.

When we're drawing the cursor, we simply call [InvertRect](https://msdn.microsoft.com/en-us/library/windows/desktop/dd145007(v=vs.85).aspx) on the region the cursor is supposed to be. I don't really know how that picks the inverse color, but it does look like 128,128,128 inverts to itself.

Not really possible for us to change that without adding support for customizable cursor colors (beyond inverting) *cough* @bitcrazed

**Comment by refack** [comment]
Can anyone comment on this ^^^. Is it a bug / new behaviour / misconfiguration?

**Comment by zadjii-msft** [comment]
I believe what you're seeing is #193 or #200. Those are fixed internally and on the way out. 

We do support changing the cursor color with VT sequences now (though we don't yet have a UI for changing the color), so I'm going to close this issue.

**Comment by refack** [comment]
Thanks
