### ISSUE TITLE
Colortool not changing the default for VS 2017 developer command prompt

### ISSUE THREAD

**Issue by dotnetdan** [Microsoft/console#58]
Please use this form and describe your issue, concisely but precisely, with as much detail as possible

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.16299.125]

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

I'm running the Developer Command Prompt for VS 2017, in admin mode. 

I run the following:

`colortool -b campbell`

This changes the color of the current session. But if I open a new instance of the developer command prompt, only the default black & white terminal colors are being used. If I open a new regular command prompt, I see that Campbell has been applied.

Is there anyway to get this to work?

* What's wrong / what should be happening instead:

Opening a new instance of Developer Command Prompt should use the new default color theme.

**Comment by zadjii-msft** [comment]
From the help text:
```
By default, applies the colors in the specified .itermcolors or .ini file to the current console window.
This does NOT save the properties automatically. For that, you'll need to open the properties sheet and hit "Ok".
```

You'll need to open the property sheet and hit okay to get the settings to persist for a particular shortcut.

**Comment by dotnetdan** [comment]
That works, thank you!

**Comment by miozus** [comment]
![image](https://user-images.githubusercontent.com/35659194/128020276-f153cadb-d96d-49c1-9575-7d331b6b8012.png)

thank you ， it mean Rclick the powershell windows — attributes — sure（ok）

to store the theme， reopen well
