### ISSUE TITLE
concfg support ?

### ISSUE THREAD

**Issue by stuaxo** [Microsoft/console#62]
https://github.com/lukesampson/concfg

concfg looks like a really interesting tool, providing a large amount of settings for the windows console.

I wonder if it's worth the color tool being able to natively import concfg json files ?

**Comment by zadjii-msft** [comment]
That would be cool to add that - though I don't think I have the cycles to be able to implement that myself. Should just be a simple JSON parser to add to the list of parsers. The other settings might be harder, but importing the colors shouldn't be too hard.

**Comment by stuaxo** [comment]
I guess, as long as it's marked as importing and not full support, that should avoid treading on any toes.

**Comment by Nacimota** [comment]
So, I had a crack at writing a simple json parser and that all works as you'd expect. But I realized after the fact that concfg does colour schemes slightly differently from our iterm/ini schemes in that it explicitly sets the screen text/background in the console properties, not just the values of the colour table. The end result is that some schemes (particularly light schemes where the background colour is set to a different index in the table) don't appear as you'd expect them to. 

I'm not sure at this stage if it's worth going to the extra effort of handling this difference in behaviour, or how best to do that.

**Comment by DarthSpock** [comment]
I filed an issue to get support from the maintainer. @Nacimota If he agrees, do you think you can work with him to bring this support? Would love to see these 2 projects working together with ease from an end user perspective.

**Comment by DarthSpock** [comment]
ping
