### ISSUE TITLE
Vim Cursor shape stays underscore. Not able to change it

### ISSUE THREAD

**Issue by bitcrazed** [Microsoft/console#68]
_From @ponegan on January 9, 2018 6:40_

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.16299.125]

* What you're doing and what's happening / What's wrong / what should be happening instead:
I'm using xterm-256color. 
I had been tried to change the shape of my vim cursor. I tried lots of different configuration for cursor shape (to be block) but none of them works as I put them in my .vimrc.

For example I tried some of these:
http://vim.wikia.com/wiki/Configuring_the_cursor

In the terminal I was able to change the shape of cursor to block by selecting 'large' in property as @zadjii-msft suggested in  #1253. But the same trick won't work for vim. Well.... it will work at the moment I set it to 'large'. But it will reset back to underscore every time I open another file.

As this:
![image](https://user-images.githubusercontent.com/35251149/34707886-e4900eb6-f4c4-11e7-89a1-8441d7c86300.png)

Anyone got a good approach on this cursor configuration? 

_Copied from original issue: Microsoft/WSL#2821_

**Comment by bitcrazed** [comment]
_From @parkovski on January 10, 2018 21:27_

I don't think this is possible right now - the console needs to understand a cursor escape, like `^[[n q` with n from 0-6, which it doesn't. The only way I know to change it right now is with console APIs that are not available within WSL. Hopefully this functionality will get implemented soon.

Edit - there may be a hacky way to do this right now. You can write a small Windows C program that calls `SetConsoleCursorInfo`, and set up vim's cursor sizing commands to run that program. I think that would work, but no guarantees.

**Comment by p-groarke** [comment]
Any updates on this? It is required for good out-of-the-box experience with vim/nvim.

**Comment by zadjii-msft** [comment]
Oh yea! I added support for cursor shapes, colors for RS5. If vim's using them to set the shape, then they should work. It's on it's way to Insiders now :)

**Comment by p-groarke** [comment]
Wow the command prompt team keeps delivering time and time again. What a time to be alive! Thanks for all the great work.

**Comment by zadjii-msft** [comment]
That's because we're the best :P

As a teaser, here's a pic of a vertical bar cursor in a pleasing cyan:
![image](https://user-images.githubusercontent.com/18356694/37678055-291d0f00-2c3a-11e8-9558-2fa6747b6289.png)

Of course, there are other shapes too if you so choose. That's just my default.

**Comment by bitcrazed** [comment]
@p-groarke Thanks for the kind words, but please stop being nice to our dev's - it makes them all happy and distracts them from their long list of bugs & features.

Back to your keyboard @zadjii-msft or I'll have to put you on notice again ;)
![backtowork](https://user-images.githubusercontent.com/961950/37690214-cee15622-2c66-11e8-9212-f4a27b51bb7e.gif)

**Comment by p-groarke** [comment]
lol!

**Comment by tuyenpm9** [comment]
Any update? really need vertical bar and block cursor to work with vim, I can't distinguish I'm in normal mode or insert mode.

**Comment by zadjii-msft** [comment]
@tuyenpm9 that's no $PS1, that's a %PROMPT% setting in CMD:
https://github.com/zadjii/keep/blob/master/bin/reprompt.cmd#L33

Also, I'm certain support for this is in Insider's (at the very least). How are you setting your cursor shape in vim?

I know that this method works at the very least: http://vim.wikia.com/wiki/Change_cursor_shape_in_different_modes#For_Terminal_on_macOS
```
let &t_SI.="\e[5 q"
let &t_SR.="\e[4 q"
let &t_EI.="\e[1 q"
```

**Comment by tuyenpm9** [comment]
I use default cursor shape in vim. I don't know what kind of terminal when running `../system32/bash.exe` but setting those in vim doesn't work, I tried others too, seem terminal forced cursor shape despite of applications. 

Non-related question: I got this error when trying to run `cmd> reprompt` - bin is in `PATH`
```
'em' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by zadjii-msft** [comment]
@tuyenpm9 What build of Windows are you running? 

The "terminal" you get when you run a commandline application on Windows is conhost.exe. It's definitely not listed on that page, but I can assure you that adding those lines to your .vimrc should work on insider's builds: (the cursor is on line 5)

Normal Mode:
![image](https://user-images.githubusercontent.com/18356694/45109911-ad8d6100-b0f5-11e8-9b09-a3d3f3ea4828.png)

Insert Mode:
![image](https://user-images.githubusercontent.com/18356694/45109928-bd0caa00-b0f5-11e8-8aa0-1ae4520bf0f1.png)


---
Are you sure that you copied the entire file? `'em'` sounds like you're missing a `@r` or possibly a `r` from the start of a `@rem` or `rem`. Can you paste the output of `reprompt` with the `@echo off` at the top commented out?

**Comment by parkovski** [comment]
Windows or Linux vim? I’ve found those cursor codes work in Linux vim but not Windows. Not sure why. Neovim on Windows does support it but you have to use `&guicursor`.

**Comment by tuyenpm9** [comment]
@parkovski : This is terminal vim.

@zadjii-msft : I use version 1709 build 16299.611, probably not insider version.

I clone `keep` repo and add bin to `PATH` and try `reprompt` on cmd, not sure why but `reprompt.cmd` is original from your repo.

**Comment by zadjii-msft** [comment]
@tuyenpm9 I don't recall when exactly I added support for cursor shapes, but I believe it was 1803. It was definitely after 1709. I'd try upgrading, that'll probably light this up for you.

----
I opened zadjii/keep#1 to track your issues with `reprompt`

**Comment by parkovski** [comment]
@tuyenpm9 - Should have been clearer, sorry. All non-terminal versions (gvim) support this via `&guicursor`. Terminal vim on Linux supports this via `&t_SI`, etc. Neovim, terminal or not, regardless of platform, supports `&guicursor`. Windows vim in the console (`vim.exe`) to my knowledge does not have support for cursor shapes. Setting `&t_SI` does _something_ in vim.exe but not the right thing.

Anyways, I don't think my question is relevant anymore due to your build number.

**Comment by kariem-ali** [comment]
It would help to know which Windows build this was fixed in. I am on Windows 10 version 1803 build number 17134.320 and I still have the issue.

**Comment by zadjii-msft** [comment]
That might by my mistake - looks like it actually wasn't merged in finally until after the cutoff for 1803, so it's not actually in 1803. I can't be sure which is the actual build number with it enabled, but it's definitely after 17134.

**Comment by kariem-ali** [comment]
I can confirm that this fix was included in Windows 10 version 1809 (Build 17763.194).

**Comment by will** [comment]
This is I suppose tangental to the issue, but I really want the cursor to change in vim. I don’t know how to get 1809. I'm on 1803 (17134.556), and there is no update available. I tried doing that insiders program, but after doing the link my account go get started, it just does a little spin, then my account never gets added. Maybe because it's an azure vm and/or the account is an alias@microsoft.com there is some restriction? (sorry I have no real idea how to use windows, which is why I'm clinging to vim and wsl as much as I can ;) )

**Comment by simlei** [comment]
I can not observe this issue is fixed. I am on Windows 10 18362, Terminal v. 0.5.2762 , PS Core 7 (Preview)
When I start vim.exe there (Terminal Vim), The cursor does not change. Am I missing something?

Thanks for the great work though!

**Comment by parkovski** [comment]
I've never been able to get the cursor change working in vim.exe and I don't know why. I mostly use neovim, and it does work there, so I think this is a vim issue now.

**Comment by ragvri** [comment]
I am on the latest version of windows (1909). I tried all the methods mentioned above on vim in WSL. Nothing works for me :/

**Comment by sleep2death** [comment]
> I am on the latest version of windows (1909). I tried all the methods mentioned above on vim in WSL. Nothing works for me :/

hi @ragvri, try install the latest "windows [terminal](https://github.com/microsoft/terminal)", and run your wsl in it.

**Comment by travisl09** [comment]
Got block/bar cursor working in powershell, cmd, and wsl with :
```
if &term == 'win32'
        let &t_ti.=" \e[1 q"
        let &t_SI.=" \e[5 q-- INSERT --"
        let &t_EI.=" \e[1 q"
        let &t_te.=" \e[0 q"
else
        let &t_ti.="\e[1 q"
        let &t_SI.="\e[5 q"
        let &t_EI.="\e[1 q"
        let &t_te.="\e[0 q"
endif
```
Note spaces before the control sequence in the win32 terminal configuration.
A few quirks but all in all much better than the cursor not indicating the current mode

Microsoft Windows [Version 10.0.18362.657] 1903
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 18 2018 18:26:56)

WSL - Ubuntu 18.04.4 LTS
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41)

**Comment by hummeleBop** [comment]
> ```
> if &term == 'win32'
>         let &t_ti.=" \e[1 q"
>         let &t_SI.=" \e[5 q-- INSERT --"
>         let &t_EI.=" \e[1 q"
>         let &t_te.=" \e[0 q"
> else
>         let &t_ti.="\e[1 q"
>         let &t_SI.="\e[5 q"
>         let &t_EI.="\e[1 q"
>         let &t_te.="\e[0 q"
> endif
> ```

Thanks for this, but somehow, it doesn't work when `set termguicolors` is enabled

**Comment by hulucc** [comment]
Nothing is work for windows terminal vim.

**Comment by j-oshb** [comment]
For what it's worth none of the above configurations are working for me.

https://github.com/microsoft/terminal/issues/68#issuecomment-621891237 is the only configuration that changes the shape at all - it changes the cursor to a block when vim starts, but then it won't change again on any mode changes.

`Windows Terminal Version: 1.0.1401.0`
`Microsoft Windows Version 10.0.18363.836`
`VIM - Vi IMproved 8.0`
`WSL Alpine`

**Comment by mbowman34** [comment]
> @tuyenpm9 that's no $PS1, that's a %PROMPT% setting in CMD:
> https://github.com/zadjii/keep/blob/master/bin/reprompt.cmd#L33
> 
> Also, I'm certain support for this is in Insider's (at the very least). How are you setting your cursor shape in vim?
> 
> I know that this method works at the very least: http://vim.wikia.com/wiki/Change_cursor_shape_in_different_modes#For_Terminal_on_macOS
> 
> ```
> let &t_SI.="\e[5 q"
> let &t_SR.="\e[4 q"
> let &t_EI.="\e[1 q"
> ```

Also can add
autocmd VimLeave * silent !echo -ne "\x1b[\x35 q"
or any value x31-x35 to set the cursor back to default after exiting vim

**Comment by gustaphe** [comment]
I thought I'd add to this because this turns up in the google results, and I've tried every combination.

What finally worked for me was
```vim
let &t_SI="\<CSI>5\ q"
let &t_SR="\<CSI>7\ q"
let &t_EI="\<CSI>2\ q"
```
There's still an issue where [the single character replace mode glitches out](https://github.com/vim/vim/issues/6576), but this fixed a lot of the visual bugs I had with other versions of this.

**Comment by mechatroner** [comment]
There is also a psychological hack: at first, the underscore cursor looks very annoying and unnatural, but after a month of usage you will be absolutely comfortable with it and even won't notice a switch between the underscore cursor and the standard block cursor when working in other environments. At least this is what happened to me.

**Comment by mbowman34** [comment]
> There is also a psychological hack: at first, the underscore cursor looks very annoying and unnatural, but after a month of usage you will be absolutely comfortable with it and even won't notice a switch between the underscore cursor and the standard block cursor when working in other environments. At least this is what happened to me.

Sure but not being able to distinguish between insert and command mode is annoying

**Comment by gustaphe** [comment]
In my case it defaulted to either vertical bar or blinking block, both if which are unacceptable.

**Comment by mbowman34** [comment]
> In my case it defaulted to either vertical bar or blinking block, both of which are unacceptable.

The default cursor for the terminal is easily configurable in settings. Just change the cursorShape for the profile you're using.

**Comment by oscarhermoso** [comment]
> Got block/bar cursor working in powershell, cmd, and wsl with :
> 
> ```
> if &term == 'win32'
>         let &t_ti.=" \e[1 q"
>         let &t_SI.=" \e[5 q-- INSERT --"
>         let &t_EI.=" \e[1 q"
>         let &t_te.=" \e[0 q"
> else
>         let &t_ti.="\e[1 q"
>         let &t_SI.="\e[5 q"
>         let &t_EI.="\e[1 q"
>         let &t_te.="\e[0 q"
> endif
> ```
> 
> Note spaces before the control sequence in the win32 terminal configuration.
> A few quirks but all in all much better than the cursor not indicating the current mode
> 
> Microsoft Windows [Version 10.0.18362.657] 1903
> VIM - Vi IMproved 8.1 (2018 May 18, compiled May 18 2018 18:26:56)
> 
> WSL - Ubuntu 18.04.4 LTS
> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41)

This saved the day for me, but there was a quirk with leaving Insert mode and keeping a vertical bar instead of a block cursor for about a second. Following [this advice](https://vi.stackexchange.com/questions/16148/slow-vim-escape-from-insert-mode), adding `set noesckeys` to my vimrc solved this for me.

**Comment by MikeClark512** [comment]
> > Got block/bar cursor working for me in wsl:
> > `let &t_ti.="\e[1 q"` 
> > `let &t_SI.="\e[5 q"`
> > `let &t_EI.="\e[1 q"`
> > `let &t_te.="\e[0 q"`    
>
> This saved the day for me, but there was a quirk with leaving Insert mode and keeping a vertical bar instead of a block cursor for about a second. 

Yes, I also immediately noticed the cursor weirdness with escaping from insert mode to normal mode.

> Following [this advice](https://vi.stackexchange.com/questions/16148/slow-vim-escape-from-insert-mode), adding `set noesckeys` to my vimrc solved this for me.

OK, but `set noesckeys` has the downside of breaking arrow keys (and other command keys that prefix with `^[`) while in insert mode. If you don't use arrow keys or some of those other commands (like home, end, pgdn, etc.) Then this will be ideal for you, but I use those keys a lot, so I need something else.

What worked better for me was to use the `ttimeoutlen` suggestion, also from the link you found (thanks!).

`set ttimeoutlen=50`

I suggest trying values of 250, 50, or 5 to balance your computer's speed with your preferences for snappiness.

**Comment by yutotakano** [comment]
The given solutions work great, but unfortunately introduces major visual glitches when `noshowmode` is set. I have no idea why, as it seems relatively unrelated, but it's definitely the culprit.

**Comment by gustaphe** [comment]
Update: My strange solution is broken/not necessary now (don't know since when), the correct method is

```vim
let &t_SI=" \e[5 q"
let &t_SR=" \e[4 q"
let &t_EI=" \e[2 q"

let &t_ti=" \e[S \e[2 q"
let &t_te=" \e[E \e[1 q"
```

(I still see the visual bug for `r`)

**Comment by hulucc** [comment]
By win32 `vim.exe`, accroding to https://github.com/microsoft/terminal/issues/10827#issuecomment-893826711, actually you should never set any of `t_SI` things, because `vim.exe` never supported this when `set term=win32'. It's not function as expect, and bring a lot of glitch.

So the workaround for win32 vim is to build a c [library](https://github.com/hulucc/vimx/releases/download/v0.0.1/libcursor.dll) do the job.
```
#include "stdio.h"

__declspec(dllexport) void setCursorType(int type) {
    printf("[%d q", type);
}
```
```
  let g:vimxdll="<path-to-libcursor.dll>"
  au InsertEnter,CmdlineEnter * :call libcall(g:vimxdll, "setCursorType", 5)
  au InsertLeave,CmdlineLeave * :call libcall(g:vimxdll, "setCursorType", 1)
  au VimLeave * :call libcall(g:vimxdll, "setCursorType", 1)
  nnoremap <silent> r :call libcall(g:vimxdll, "setCursorType", 3)<cr>:au TextChanged,CursorMoved * ++once :call libcall(g:vimxdll, "setCursorType", 1)<cr>r
```

**Comment by gustaphe** [comment]
> So the workaround for win32 vim is to build a c [library](https://github.com/hulucc/vimx/releases/download/v0.0.1/libcursor.dll) do the job.

I'd be happy to use this if it worked, but I can't seem to get anything but E364 on Windows. If you have any time to help me debug this [maybe we can take the discussion here](https://github.com/gustaphe/winterm.vim).

**Comment by gustaphe** [comment]
I turned @hulucc's comment into [a plugin](https://github.com/gustaphe/winterm.vim).
