### ISSUE TITLE
Consider targeting at 4.6.x for a better OOTB experience.

### ISSUE THREAD

**Issue by oising** [Microsoft/console#7]
Is targeting .NET Framework 4.7 really neccessary for ColorTool?

**Comment by oising** [comment]
I edited the csproj to target v4.6 and it compiled fine, so I'd say the answer to this is a resounding no -- 4.7 is just blocking regular w10 users who have 4.6.2 ootb.

**Comment by oising** [comment]
PR submitted *COUGH*

**Comment by charlesmilette** [comment]
*cough* Pull Request *cough*

As for targeting 4.7:

You need to build this yourself, and the base Visual Studio 2017 install (as older versions aren't available anymore) for building C# code comes with the 4.7 SDK so this would only block people with older versions of Visual Studio.

**Comment by oising** [comment]
Right, 4.7 is in an _optional_ component, but the default workloads for desktop and web use 4.6.1. 

![image](https://user-images.githubusercontent.com/1844001/29253003-e29b2fd0-8040-11e7-9326-3703b5a5c671.png)

**Comment by charlesmilette** [comment]
My bad then, ignore what i said

**Comment by khouzam** [comment]
This has been merged

**Comment by PhMajerus** [comment]
Sorry for the reference, #7 was in the text to describe the number, it wasn't related to this other issue but got automatically processed as such.
