### ISSUE TITLE
Broken rendering of Midnight Commander (Ncurses console application)

### ISSUE THREAD

**Issue by bitcrazed** [Microsoft/console#80]
_From @viktor-ferenczi on October 13, 2017 11:49_

Windows 10 64bit vesion 1703 build 15063.674 English

**How to reproduce**

1. Install Midnight Commander by: `apt-get install mc`
2. Start Midnight Commander: `mc`
3. Rendering will have black areas, already broken
4. To reproduce the behavior on the screenshot open the menu by pressing F9, then press ENTER to drop down the menu, then press Left/Right arrows to navigate between the menus

**Screenshot**

![image](https://user-images.githubusercontent.com/1848514/31544765-b8b10a80-b01c-11e7-83bd-13ddb1240f42.png)

_Copied from original issue: Microsoft/WSL#2564_

**Comment by bitcrazed** [comment]
_From @zadjii-msft on October 13, 2017 20:15_

There's a REALLY good chance that the fix for this is coming in Fall Creator's Update. I fixed a bunch of stuff regarding box drawing characters and `mc`, I would upgrade and see if that fixes it for you.

see #2099, #1879 and everything linked to those guys.

**Comment by bitcrazed** [comment]
_From @Yay295 on October 25, 2017 15:59_

@viktor-ferenczi, has this been fixed with the Fall Creators update?

**Comment by Yay295** [comment]
This seems to have been fixed with Redstone 4, though I haven't extensively tested it.

**Comment by bitcrazed** [comment]
Should now be fixed. Let us know if you can repro in 1803 or newer builds.
